// Code generated by protoc-gen-go.
// source: gamemsg.proto
// DO NOT EDIT!

/*
Package gamemsg is a generated protocol buffer package.

It is generated from these files:
	gamemsg.proto

It has these top-level messages:
	PB_PlayerProperty
	PB_Player
	CS21001
	SC21002
*/
package gamemsg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PB_PlayerProperty_PB_RolePropertyType int32

const (
	PB_PlayerProperty_level    PB_PlayerProperty_PB_RolePropertyType = 0
	PB_PlayerProperty_exp      PB_PlayerProperty_PB_RolePropertyType = 1
	PB_PlayerProperty_max_exp  PB_PlayerProperty_PB_RolePropertyType = 2
	PB_PlayerProperty_gold     PB_PlayerProperty_PB_RolePropertyType = 3
	PB_PlayerProperty_diamonds PB_PlayerProperty_PB_RolePropertyType = 4
)

var PB_PlayerProperty_PB_RolePropertyType_name = map[int32]string{
	0: "level",
	1: "exp",
	2: "max_exp",
	3: "gold",
	4: "diamonds",
}
var PB_PlayerProperty_PB_RolePropertyType_value = map[string]int32{
	"level":    0,
	"exp":      1,
	"max_exp":  2,
	"gold":     3,
	"diamonds": 4,
}

func (x PB_PlayerProperty_PB_RolePropertyType) String() string {
	return proto.EnumName(PB_PlayerProperty_PB_RolePropertyType_name, int32(x))
}
func (PB_PlayerProperty_PB_RolePropertyType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0}
}

type PB_Player_PB_RoleType int32

const (
	PB_Player_PB_RoleType_Nan PB_Player_PB_RoleType = 0
	PB_Player_PB_RoleType_Nv  PB_Player_PB_RoleType = 1
)

var PB_Player_PB_RoleType_name = map[int32]string{
	0: "PB_RoleType_Nan",
	1: "PB_RoleType_Nv",
}
var PB_Player_PB_RoleType_value = map[string]int32{
	"PB_RoleType_Nan": 0,
	"PB_RoleType_Nv":  1,
}

func (x PB_Player_PB_RoleType) String() string {
	return proto.EnumName(PB_Player_PB_RoleType_name, int32(x))
}
func (PB_Player_PB_RoleType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type CS21001_PacketType int32

const (
	CS21001_PB_Temp        CS21001_PacketType = 0
	CS21001_PB_PackType    CS21001_PacketType = 21001
	CS21001_PB_PackRetType CS21001_PacketType = 21002
)

var CS21001_PacketType_name = map[int32]string{
	0:     "PB_Temp",
	21001: "PB_PackType",
	21002: "PB_PackRetType",
}
var CS21001_PacketType_value = map[string]int32{
	"PB_Temp":        0,
	"PB_PackType":    21001,
	"PB_PackRetType": 21002,
}

func (x CS21001_PacketType) String() string {
	return proto.EnumName(CS21001_PacketType_name, int32(x))
}
func (CS21001_PacketType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

type SC21002_PacketType int32

const (
	SC21002_PB_Temp     SC21002_PacketType = 0
	SC21002_PB_PackType SC21002_PacketType = 21002
)

var SC21002_PacketType_name = map[int32]string{
	0:     "PB_Temp",
	21002: "PB_PackType",
}
var SC21002_PacketType_value = map[string]int32{
	"PB_Temp":     0,
	"PB_PackType": 21002,
}

func (x SC21002_PacketType) String() string {
	return proto.EnumName(SC21002_PacketType_name, int32(x))
}
func (SC21002_PacketType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

type PB_PlayerProperty struct {
	Type  PB_PlayerProperty_PB_RolePropertyType `protobuf:"varint,1,opt,name=type,enum=gamemsg.PB_PlayerProperty_PB_RolePropertyType" json:"type,omitempty"`
	Value int64                                 `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
}

func (m *PB_PlayerProperty) Reset()                    { *m = PB_PlayerProperty{} }
func (m *PB_PlayerProperty) String() string            { return proto.CompactTextString(m) }
func (*PB_PlayerProperty) ProtoMessage()               {}
func (*PB_PlayerProperty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type PB_Player struct {
	Name       string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	RoleType   PB_Player_PB_RoleType `protobuf:"varint,2,opt,name=roleType,enum=gamemsg.PB_Player_PB_RoleType" json:"roleType,omitempty"`
	PlayerProp *PB_PlayerProperty    `protobuf:"bytes,3,opt,name=playerProp" json:"playerProp,omitempty"`
}

func (m *PB_Player) Reset()                    { *m = PB_Player{} }
func (m *PB_Player) String() string            { return proto.CompactTextString(m) }
func (*PB_Player) ProtoMessage()               {}
func (*PB_Player) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PB_Player) GetPlayerProp() *PB_PlayerProperty {
	if m != nil {
		return m.PlayerProp
	}
	return nil
}

// 玩家登陆 CS21001（第三方登陆或本地测试登陆都使用该协议）
type CS21001 struct {
	AccountId int64  `protobuf:"varint,1,opt,name=accountId" json:"accountId,omitempty"`
	SessionId string `protobuf:"bytes,2,opt,name=sessionId" json:"sessionId,omitempty"`
	ServerId  int32  `protobuf:"varint,3,opt,name=serverId" json:"serverId,omitempty"`
}

func (m *CS21001) Reset()                    { *m = CS21001{} }
func (m *CS21001) String() string            { return proto.CompactTextString(m) }
func (*CS21001) ProtoMessage()               {}
func (*CS21001) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// 登陆返回 SC12002
type SC21002 struct {
	Player *PB_Player `protobuf:"bytes,1,opt,name=player" json:"player,omitempty"`
}

func (m *SC21002) Reset()                    { *m = SC21002{} }
func (m *SC21002) String() string            { return proto.CompactTextString(m) }
func (*SC21002) ProtoMessage()               {}
func (*SC21002) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SC21002) GetPlayer() *PB_Player {
	if m != nil {
		return m.Player
	}
	return nil
}

func init() {
	proto.RegisterType((*PB_PlayerProperty)(nil), "gamemsg.PB_PlayerProperty")
	proto.RegisterType((*PB_Player)(nil), "gamemsg.PB_Player")
	proto.RegisterType((*CS21001)(nil), "gamemsg.CS21001")
	proto.RegisterType((*SC21002)(nil), "gamemsg.SC21002")
	proto.RegisterEnum("gamemsg.PB_PlayerProperty_PB_RolePropertyType", PB_PlayerProperty_PB_RolePropertyType_name, PB_PlayerProperty_PB_RolePropertyType_value)
	proto.RegisterEnum("gamemsg.PB_Player_PB_RoleType", PB_Player_PB_RoleType_name, PB_Player_PB_RoleType_value)
	proto.RegisterEnum("gamemsg.CS21001_PacketType", CS21001_PacketType_name, CS21001_PacketType_value)
	proto.RegisterEnum("gamemsg.SC21002_PacketType", SC21002_PacketType_name, SC21002_PacketType_value)
}

func init() { proto.RegisterFile("gamemsg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 400 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x92, 0x41, 0x6a, 0xdb, 0x40,
	0x14, 0x86, 0x3d, 0x91, 0x1d, 0x59, 0x4f, 0xad, 0x3b, 0x79, 0xc9, 0xc2, 0x84, 0x52, 0xcc, 0xac,
	0x4c, 0x29, 0x26, 0x51, 0xa1, 0x8b, 0x2c, 0x95, 0x95, 0x37, 0x41, 0x4c, 0xb2, 0x17, 0x53, 0xe9,
	0x61, 0x42, 0x25, 0x8d, 0x90, 0x14, 0x11, 0x1d, 0xa1, 0x39, 0x87, 0x7b, 0x8c, 0x9e, 0xa1, 0x57,
	0x2a, 0x33, 0x8a, 0x65, 0x17, 0xb7, 0xd0, 0x9d, 0xfe, 0xff, 0xbd, 0x5f, 0xf3, 0xfd, 0xc3, 0xc0,
	0xdb, 0x8d, 0xca, 0x29, 0xaf, 0x37, 0xab, 0xb2, 0xd2, 0x8d, 0x46, 0xf7, 0x55, 0x8a, 0x9f, 0x0c,
	0xce, 0xa2, 0x30, 0x8e, 0x32, 0xd5, 0x51, 0x15, 0x55, 0xba, 0xa4, 0xaa, 0xe9, 0x30, 0x84, 0x71,
	0xd3, 0x95, 0x34, 0x67, 0x0b, 0xb6, 0x9c, 0x05, 0xab, 0xd5, 0x2e, 0x7c, 0xb4, 0x69, 0x1c, 0xa9,
	0x33, 0xda, 0xe9, 0x87, 0xae, 0x24, 0x69, 0xb3, 0x78, 0x01, 0x93, 0x56, 0x65, 0x4f, 0x34, 0x3f,
	0x59, 0xb0, 0xa5, 0x23, 0x7b, 0x21, 0xee, 0xe0, 0xfc, 0x2f, 0x11, 0xf4, 0x60, 0x92, 0x51, 0x4b,
	0x19, 0x1f, 0xa1, 0x0b, 0x0e, 0x3d, 0x97, 0x9c, 0xa1, 0x0f, 0x6e, 0xae, 0x9e, 0x63, 0x23, 0x4e,
	0x70, 0x0a, 0xe3, 0x8d, 0xce, 0x52, 0xee, 0xe0, 0x1b, 0x98, 0xa6, 0x8f, 0x2a, 0xd7, 0x45, 0x5a,
	0xf3, 0xb1, 0xf8, 0xc5, 0xc0, 0x1b, 0xa8, 0x10, 0x61, 0x5c, 0xa8, 0xbc, 0xe7, 0xf6, 0xa4, 0xfd,
	0xc6, 0x1b, 0x98, 0x56, 0x3a, 0x23, 0x73, 0x8c, 0x45, 0x99, 0x05, 0x1f, 0x8e, 0xfb, 0xec, 0x7a,
	0x58, 0xfe, 0x61, 0x1f, 0x6f, 0x00, 0xca, 0xa1, 0xef, 0xdc, 0x59, 0xb0, 0xa5, 0x1f, 0x5c, 0xfe,
	0xfb, 0x36, 0xe4, 0xc1, 0xb6, 0xf8, 0x02, 0xfe, 0xc1, 0x4f, 0xf1, 0x1c, 0xde, 0x1d, 0xc8, 0xf8,
	0x4e, 0x15, 0x7c, 0x84, 0x08, 0xb3, 0x3f, 0xcc, 0x96, 0x33, 0xf1, 0x83, 0x81, 0x7b, 0x7b, 0x1f,
	0x5c, 0x5f, 0x5d, 0x5d, 0xe3, 0x7b, 0xf0, 0x54, 0x92, 0xe8, 0xa7, 0xa2, 0x59, 0xa7, 0xb6, 0x94,
	0x23, 0xf7, 0x86, 0x99, 0xd6, 0x54, 0xd7, 0x8f, 0xba, 0x58, 0xa7, 0xb6, 0x9a, 0x27, 0xf7, 0x06,
	0x5e, 0xc2, 0xb4, 0xa6, 0xaa, 0xa5, 0x6a, 0x9d, 0x5a, 0xf2, 0x89, 0x1c, 0xb4, 0x08, 0x01, 0x22,
	0x95, 0x7c, 0xa3, 0xc6, 0xa2, 0xf9, 0xe0, 0x46, 0x61, 0xfc, 0x40, 0x79, 0xc9, 0x47, 0x78, 0x66,
	0xb1, 0xcd, 0xd4, 0xcc, 0xf8, 0xf7, 0x2d, 0xc3, 0x0b, 0x4b, 0x69, 0x2c, 0xd9, 0x27, 0xf8, 0xcb,
	0x96, 0x89, 0x04, 0xdc, 0xfb, 0x5b, 0x83, 0x19, 0xe0, 0x47, 0x38, 0xed, 0x8b, 0x5b, 0x46, 0x3f,
	0xc0, 0xe3, 0x2b, 0x92, 0xaf, 0x1b, 0xe2, 0xd3, 0x7f, 0x1f, 0xfd, 0xb2, 0x65, 0x5f, 0x4f, 0xed,
	0x73, 0xfd, 0xfc, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xd5, 0xd9, 0x24, 0xf3, 0xbf, 0x02, 0x00, 0x00,
}
