// Code generated by protoc-gen-go.
// source: loginmsg.proto
// DO NOT EDIT!

/*
Package loginmsg is a generated protocol buffer package.

It is generated from these files:
	loginmsg.proto

It has these top-level messages:
	PB_ServerInfo
	PB_AccountLoginHistory
	CS11001
	SC11002
*/
package loginmsg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PB_ServerInfo_PB_ServerStatus int32

const (
	PB_ServerInfo_good     PB_ServerInfo_PB_ServerStatus = 0
	PB_ServerInfo_crowd    PB_ServerInfo_PB_ServerStatus = 1
	PB_ServerInfo_busy     PB_ServerInfo_PB_ServerStatus = 2
	PB_ServerInfo_maintain PB_ServerInfo_PB_ServerStatus = 3
)

var PB_ServerInfo_PB_ServerStatus_name = map[int32]string{
	0: "good",
	1: "crowd",
	2: "busy",
	3: "maintain",
}
var PB_ServerInfo_PB_ServerStatus_value = map[string]int32{
	"good":     0,
	"crowd":    1,
	"busy":     2,
	"maintain": 3,
}

func (x PB_ServerInfo_PB_ServerStatus) String() string {
	return proto.EnumName(PB_ServerInfo_PB_ServerStatus_name, int32(x))
}
func (PB_ServerInfo_PB_ServerStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0}
}

type PB_AccountLoginHistory_PB_LoginRoleTye int32

const (
	PB_AccountLoginHistory_man   PB_AccountLoginHistory_PB_LoginRoleTye = 0
	PB_AccountLoginHistory_women PB_AccountLoginHistory_PB_LoginRoleTye = 1
)

var PB_AccountLoginHistory_PB_LoginRoleTye_name = map[int32]string{
	0: "man",
	1: "women",
}
var PB_AccountLoginHistory_PB_LoginRoleTye_value = map[string]int32{
	"man":   0,
	"women": 1,
}

func (x PB_AccountLoginHistory_PB_LoginRoleTye) String() string {
	return proto.EnumName(PB_AccountLoginHistory_PB_LoginRoleTye_name, int32(x))
}
func (PB_AccountLoginHistory_PB_LoginRoleTye) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 0}
}

type CS11001_PacketType int32

const (
	CS11001_PB_Temp        CS11001_PacketType = 0
	CS11001_PB_PackType    CS11001_PacketType = 11001
	CS11001_PB_PackRetType CS11001_PacketType = 11002
)

var CS11001_PacketType_name = map[int32]string{
	0:     "PB_Temp",
	11001: "PB_PackType",
	11002: "PB_PackRetType",
}
var CS11001_PacketType_value = map[string]int32{
	"PB_Temp":        0,
	"PB_PackType":    11001,
	"PB_PackRetType": 11002,
}

func (x CS11001_PacketType) String() string {
	return proto.EnumName(CS11001_PacketType_name, int32(x))
}
func (CS11001_PacketType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

type CS11001_PB_PlatformType int32

const (
	CS11001_local_test  CS11001_PB_PlatformType = 0
	CS11001_local_login CS11001_PB_PlatformType = 1
)

var CS11001_PB_PlatformType_name = map[int32]string{
	0: "local_test",
	1: "local_login",
}
var CS11001_PB_PlatformType_value = map[string]int32{
	"local_test":  0,
	"local_login": 1,
}

func (x CS11001_PB_PlatformType) String() string {
	return proto.EnumName(CS11001_PB_PlatformType_name, int32(x))
}
func (CS11001_PB_PlatformType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 1} }

type SC11002_PacketType int32

const (
	SC11002_PB_Temp     SC11002_PacketType = 0
	SC11002_PB_PackType SC11002_PacketType = 11002
)

var SC11002_PacketType_name = map[int32]string{
	0:     "PB_Temp",
	11002: "PB_PackType",
}
var SC11002_PacketType_value = map[string]int32{
	"PB_Temp":     0,
	"PB_PackType": 11002,
}

func (x SC11002_PacketType) String() string {
	return proto.EnumName(SC11002_PacketType_name, int32(x))
}
func (SC11002_PacketType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

type PB_ServerInfo struct {
	ServerId   int32                         `protobuf:"varint,1,opt,name=serverId" json:"serverId,omitempty"`
	ServerName string                        `protobuf:"bytes,2,opt,name=serverName" json:"serverName,omitempty"`
	ServerUrl  string                        `protobuf:"bytes,3,opt,name=serverUrl" json:"serverUrl,omitempty"`
	Status     PB_ServerInfo_PB_ServerStatus `protobuf:"varint,4,opt,name=status,enum=loginmsg.PB_ServerInfo_PB_ServerStatus" json:"status,omitempty"`
}

func (m *PB_ServerInfo) Reset()                    { *m = PB_ServerInfo{} }
func (m *PB_ServerInfo) String() string            { return proto.CompactTextString(m) }
func (*PB_ServerInfo) ProtoMessage()               {}
func (*PB_ServerInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type PB_AccountLoginHistory struct {
	ServerId   int32                                  `protobuf:"varint,1,opt,name=serverId" json:"serverId,omitempty"`
	RoleType   PB_AccountLoginHistory_PB_LoginRoleTye `protobuf:"varint,2,opt,name=roleType,enum=loginmsg.PB_AccountLoginHistory_PB_LoginRoleTye" json:"roleType,omitempty"`
	RoleName   string                                 `protobuf:"bytes,3,opt,name=roleName" json:"roleName,omitempty"`
	RoleLevel  int32                                  `protobuf:"varint,4,opt,name=roleLevel" json:"roleLevel,omitempty"`
	AwakeLevel int32                                  `protobuf:"varint,5,opt,name=awakeLevel" json:"awakeLevel,omitempty"`
	VipLevel   int32                                  `protobuf:"varint,6,opt,name=vipLevel" json:"vipLevel,omitempty"`
	UpdateTime int64                                  `protobuf:"varint,7,opt,name=updateTime" json:"updateTime,omitempty"`
}

func (m *PB_AccountLoginHistory) Reset()                    { *m = PB_AccountLoginHistory{} }
func (m *PB_AccountLoginHistory) String() string            { return proto.CompactTextString(m) }
func (*PB_AccountLoginHistory) ProtoMessage()               {}
func (*PB_AccountLoginHistory) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// 玩家登陆 CS11001（第三方登陆或本地测试登陆都使用该协议）
type CS11001 struct {
	PlatformType CS11001_PB_PlatformType `protobuf:"varint,1,opt,name=platformType,enum=loginmsg.CS11001_PB_PlatformType" json:"platformType,omitempty"`
	// 账号信息
	Account  string `protobuf:"bytes,2,opt,name=account" json:"account,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	// 客户端硬件信息
	ClientType string `protobuf:"bytes,4,opt,name=clientType" json:"clientType,omitempty"`
	Uuid       string `protobuf:"bytes,5,opt,name=uuid" json:"uuid,omitempty"`
}

func (m *CS11001) Reset()                    { *m = CS11001{} }
func (m *CS11001) String() string            { return proto.CompactTextString(m) }
func (*CS11001) ProtoMessage()               {}
func (*CS11001) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// 登陆返回 SC11002
type SC11002 struct {
	SessionId      string                    `protobuf:"bytes,1,opt,name=sessionId" json:"sessionId,omitempty"`
	PlayerId       int64                     `protobuf:"varint,2,opt,name=playerId" json:"playerId,omitempty"`
	LoginHistories []*PB_AccountLoginHistory `protobuf:"bytes,3,rep,name=loginHistories" json:"loginHistories,omitempty"`
	ServerInfos    []*PB_ServerInfo          `protobuf:"bytes,4,rep,name=serverInfos" json:"serverInfos,omitempty"`
}

func (m *SC11002) Reset()                    { *m = SC11002{} }
func (m *SC11002) String() string            { return proto.CompactTextString(m) }
func (*SC11002) ProtoMessage()               {}
func (*SC11002) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SC11002) GetLoginHistories() []*PB_AccountLoginHistory {
	if m != nil {
		return m.LoginHistories
	}
	return nil
}

func (m *SC11002) GetServerInfos() []*PB_ServerInfo {
	if m != nil {
		return m.ServerInfos
	}
	return nil
}

func init() {
	proto.RegisterType((*PB_ServerInfo)(nil), "loginmsg.PB_ServerInfo")
	proto.RegisterType((*PB_AccountLoginHistory)(nil), "loginmsg.PB_AccountLoginHistory")
	proto.RegisterType((*CS11001)(nil), "loginmsg.CS11001")
	proto.RegisterType((*SC11002)(nil), "loginmsg.SC11002")
	proto.RegisterEnum("loginmsg.PB_ServerInfo_PB_ServerStatus", PB_ServerInfo_PB_ServerStatus_name, PB_ServerInfo_PB_ServerStatus_value)
	proto.RegisterEnum("loginmsg.PB_AccountLoginHistory_PB_LoginRoleTye", PB_AccountLoginHistory_PB_LoginRoleTye_name, PB_AccountLoginHistory_PB_LoginRoleTye_value)
	proto.RegisterEnum("loginmsg.CS11001_PacketType", CS11001_PacketType_name, CS11001_PacketType_value)
	proto.RegisterEnum("loginmsg.CS11001_PB_PlatformType", CS11001_PB_PlatformType_name, CS11001_PB_PlatformType_value)
	proto.RegisterEnum("loginmsg.SC11002_PacketType", SC11002_PacketType_name, SC11002_PacketType_value)
}

func init() { proto.RegisterFile("loginmsg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 568 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x94, 0x5d, 0x8b, 0xda, 0x4c,
	0x14, 0xc7, 0x8d, 0x51, 0xa3, 0xc7, 0x7d, 0xdc, 0x61, 0x1e, 0x68, 0x43, 0x29, 0x25, 0x0d, 0x94,
	0x0a, 0x85, 0x45, 0xed, 0x55, 0x6f, 0xfa, 0xe2, 0x52, 0xd8, 0x82, 0x14, 0x19, 0xf5, 0x5a, 0x66,
	0x93, 0x59, 0x09, 0x26, 0x99, 0x90, 0x99, 0x28, 0x7e, 0xab, 0x7e, 0x83, 0x7e, 0x9f, 0xde, 0xf7,
	0xa2, 0x7b, 0x55, 0x66, 0x26, 0xc6, 0xb8, 0xf4, 0xed, 0x6e, 0xfe, 0xff, 0x33, 0x67, 0x72, 0xce,
	0xcf, 0x73, 0x84, 0x41, 0xcc, 0x37, 0x51, 0x9a, 0x88, 0xcd, 0x55, 0x96, 0x73, 0xc9, 0x71, 0xf7,
	0xa8, 0xfd, 0x6f, 0x16, 0xfc, 0x37, 0x9f, 0xae, 0x17, 0x2c, 0xdf, 0xb1, 0xfc, 0x53, 0x7a, 0xc7,
	0xf1, 0x13, 0xe8, 0x0a, 0xa3, 0x42, 0xd7, 0xf2, 0xac, 0x61, 0x9b, 0x54, 0x1a, 0x3f, 0x03, 0x30,
	0xe7, 0xcf, 0x34, 0x61, 0x6e, 0xd3, 0xb3, 0x86, 0x3d, 0x52, 0x73, 0xf0, 0x53, 0xe8, 0x19, 0xb5,
	0xca, 0x63, 0xd7, 0xd6, 0xe1, 0x93, 0x81, 0xdf, 0x41, 0x47, 0x48, 0x2a, 0x0b, 0xe1, 0xb6, 0x3c,
	0x6b, 0x38, 0x98, 0xbc, 0xbc, 0xaa, 0xca, 0x3a, 0x2b, 0xe1, 0xa4, 0x16, 0xfa, 0x3a, 0x29, 0xd3,
	0xfc, 0xb7, 0x70, 0xf9, 0x20, 0x84, 0xbb, 0xd0, 0xda, 0x70, 0x1e, 0xa2, 0x06, 0xee, 0x41, 0x3b,
	0xc8, 0xf9, 0x3e, 0x44, 0x96, 0x32, 0x6f, 0x0b, 0x71, 0x40, 0x4d, 0x7c, 0x01, 0xdd, 0x84, 0x46,
	0xa9, 0xa4, 0x51, 0x8a, 0x6c, 0xff, 0x6b, 0x13, 0x1e, 0xcd, 0xa7, 0xeb, 0x0f, 0x41, 0xc0, 0x8b,
	0x54, 0xce, 0xd4, 0xc7, 0x6f, 0x22, 0x21, 0x79, 0x7e, 0xf8, 0x63, 0xd7, 0x33, 0xe8, 0xe6, 0x3c,
	0x66, 0xcb, 0x43, 0x66, 0x7a, 0x1e, 0x4c, 0x46, 0x67, 0x95, 0xff, 0xe2, 0x3d, 0x65, 0x6b, 0x4d,
	0x74, 0x22, 0x23, 0xd5, 0x0b, 0xea, 0x4b, 0xea, 0xac, 0x09, 0x1a, 0x44, 0x95, 0x56, 0xfc, 0xd4,
	0x79, 0xc6, 0x76, 0x2c, 0xd6, 0x90, 0xda, 0xe4, 0x64, 0x28, 0xfa, 0x74, 0x4f, 0xb7, 0x65, 0xb8,
	0xad, 0xc3, 0x35, 0x47, 0xbd, 0xbc, 0x8b, 0x32, 0x13, 0xed, 0x98, 0x1e, 0x8e, 0x5a, 0xe5, 0x16,
	0x59, 0x48, 0x25, 0x5b, 0x46, 0x09, 0x73, 0x1d, 0xcf, 0x1a, 0xda, 0xa4, 0xe6, 0xf8, 0x2f, 0x34,
	0xda, 0x7a, 0xc9, 0xd8, 0x01, 0x3b, 0xa1, 0xa9, 0x21, 0xbb, 0xe7, 0x09, 0x4b, 0x91, 0xe5, 0x7f,
	0x69, 0x82, 0x73, 0xbd, 0x18, 0x8f, 0x47, 0xa3, 0x31, 0xfe, 0x08, 0x17, 0x59, 0x4c, 0xe5, 0x1d,
	0xcf, 0x13, 0x8d, 0xc6, 0xd2, 0x68, 0x9e, 0x9f, 0xd0, 0x94, 0x17, 0x15, 0x8b, 0x79, 0xed, 0x22,
	0x39, 0x4b, 0xc3, 0x2e, 0x38, 0xd4, 0x00, 0x2c, 0x07, 0xea, 0x28, 0x55, 0x3f, 0x19, 0x15, 0x62,
	0xcf, 0xf3, 0xf0, 0x48, 0xea, 0xa8, 0x55, 0x3f, 0x41, 0x1c, 0xb1, 0x54, 0xea, 0x4f, 0xb7, 0xcc,
	0x24, 0x9e, 0x1c, 0x8c, 0xa1, 0x55, 0x14, 0x51, 0xa8, 0x29, 0xf5, 0x88, 0x3e, 0xfb, 0xef, 0x01,
	0xe6, 0x34, 0xd8, 0x32, 0x73, 0xa3, 0x0f, 0xce, 0x7c, 0xba, 0x5e, 0xb2, 0x24, 0x43, 0x0d, 0x8c,
	0xa0, 0xaf, 0xaa, 0xa4, 0xc1, 0x56, 0xc5, 0xd0, 0x8f, 0x15, 0xfe, 0x1f, 0x06, 0xa5, 0x43, 0x4c,
	0x02, 0xba, 0x5f, 0xf9, 0x13, 0x4d, 0xa9, 0xde, 0x0c, 0x1e, 0x00, 0xc4, 0x3c, 0xa0, 0xf1, 0x5a,
	0x32, 0x21, 0x51, 0x03, 0x5f, 0x42, 0xdf, 0x68, 0x8d, 0x01, 0x59, 0xfe, 0x77, 0x0b, 0x9c, 0xc5,
	0xb5, 0x22, 0x31, 0x31, 0xfb, 0x21, 0x44, 0xc4, 0xd3, 0x72, 0xcc, 0xf4, 0x7e, 0x94, 0x86, 0xee,
	0x37, 0xa6, 0x07, 0x3d, 0x83, 0x4d, 0xfd, 0x0b, 0x55, 0x1a, 0xdf, 0x94, 0x3b, 0x6c, 0xe6, 0x2b,
	0x62, 0xc2, 0xb5, 0x3d, 0x7b, 0xd8, 0x9f, 0x78, 0x7f, 0x9b, 0x44, 0xf2, 0x20, 0x0f, 0xbf, 0x81,
	0xbe, 0xa8, 0x56, 0x4d, 0xad, 0xa2, 0x7a, 0xe6, 0xf1, 0x6f, 0x56, 0x91, 0xd4, 0xef, 0xfa, 0xaf,
	0xfe, 0x19, 0xe0, 0xfd, 0xea, 0xb6, 0xa3, 0xff, 0x6a, 0x5e, 0xff, 0x0c, 0x00, 0x00, 0xff, 0xff,
	0xb8, 0x4b, 0x87, 0x0b, 0x7c, 0x04, 0x00, 0x00,
}
