// Code generated by protoc-gen-go.
// source: PB_Login.proto
// DO NOT EDIT!

/*
Package PB_login is a generated protocol buffer package.

It is generated from these files:
	PB_Login.proto

It has these top-level messages:
	PB_ServerInfo
	PB_AccountLoginHistory
	CS11001
	SC11002
*/
package PB_login

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PB_ServerInfo_PB_ServerStatus int32

const (
	PB_ServerInfo_good     PB_ServerInfo_PB_ServerStatus = 0
	PB_ServerInfo_crowd    PB_ServerInfo_PB_ServerStatus = 1
	PB_ServerInfo_busy     PB_ServerInfo_PB_ServerStatus = 2
	PB_ServerInfo_maintain PB_ServerInfo_PB_ServerStatus = 3
)

var PB_ServerInfo_PB_ServerStatus_name = map[int32]string{
	0: "good",
	1: "crowd",
	2: "busy",
	3: "maintain",
}
var PB_ServerInfo_PB_ServerStatus_value = map[string]int32{
	"good":     0,
	"crowd":    1,
	"busy":     2,
	"maintain": 3,
}

func (x PB_ServerInfo_PB_ServerStatus) String() string {
	return proto.EnumName(PB_ServerInfo_PB_ServerStatus_name, int32(x))
}
func (PB_ServerInfo_PB_ServerStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0}
}

type PB_AccountLoginHistory_PB_LoginRoleTye int32

const (
	PB_AccountLoginHistory_man   PB_AccountLoginHistory_PB_LoginRoleTye = 0
	PB_AccountLoginHistory_women PB_AccountLoginHistory_PB_LoginRoleTye = 1
)

var PB_AccountLoginHistory_PB_LoginRoleTye_name = map[int32]string{
	0: "man",
	1: "women",
}
var PB_AccountLoginHistory_PB_LoginRoleTye_value = map[string]int32{
	"man":   0,
	"women": 1,
}

func (x PB_AccountLoginHistory_PB_LoginRoleTye) String() string {
	return proto.EnumName(PB_AccountLoginHistory_PB_LoginRoleTye_name, int32(x))
}
func (PB_AccountLoginHistory_PB_LoginRoleTye) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 0}
}

type CS11001_PB_PlatformType int32

const (
	CS11001_local_login    CS11001_PB_PlatformType = 0
	CS11001_platform_login CS11001_PB_PlatformType = 1
)

var CS11001_PB_PlatformType_name = map[int32]string{
	0: "local_login",
	1: "platform_login",
}
var CS11001_PB_PlatformType_value = map[string]int32{
	"local_login":    0,
	"platform_login": 1,
}

func (x CS11001_PB_PlatformType) String() string {
	return proto.EnumName(CS11001_PB_PlatformType_name, int32(x))
}
func (CS11001_PB_PlatformType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

// ***********************************************************************
// Modul
// **********************************************************************
type PB_ServerInfo struct {
	ServerId   int32                         `protobuf:"varint,1,opt,name=serverId" json:"serverId,omitempty"`
	ServerName string                        `protobuf:"bytes,2,opt,name=serverName" json:"serverName,omitempty"`
	ServerUrl  string                        `protobuf:"bytes,3,opt,name=serverUrl" json:"serverUrl,omitempty"`
	TcpIp      string                        `protobuf:"bytes,4,opt,name=tcpIp" json:"tcpIp,omitempty"`
	TcpPort    string                        `protobuf:"bytes,5,opt,name=tcpPort" json:"tcpPort,omitempty"`
	Status     PB_ServerInfo_PB_ServerStatus `protobuf:"varint,6,opt,name=status,enum=PB_login.PB_ServerInfo_PB_ServerStatus" json:"status,omitempty"`
}

func (m *PB_ServerInfo) Reset()                    { *m = PB_ServerInfo{} }
func (m *PB_ServerInfo) String() string            { return proto.CompactTextString(m) }
func (*PB_ServerInfo) ProtoMessage()               {}
func (*PB_ServerInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type PB_AccountLoginHistory struct {
	ServerId   int32                                  `protobuf:"varint,1,opt,name=serverId" json:"serverId,omitempty"`
	RoleType   PB_AccountLoginHistory_PB_LoginRoleTye `protobuf:"varint,2,opt,name=roleType,enum=PB_login.PB_AccountLoginHistory_PB_LoginRoleTye" json:"roleType,omitempty"`
	RoleName   string                                 `protobuf:"bytes,3,opt,name=roleName" json:"roleName,omitempty"`
	RoleLevel  int32                                  `protobuf:"varint,4,opt,name=roleLevel" json:"roleLevel,omitempty"`
	AwakeLevel int32                                  `protobuf:"varint,5,opt,name=awakeLevel" json:"awakeLevel,omitempty"`
	VipLevel   int32                                  `protobuf:"varint,6,opt,name=vipLevel" json:"vipLevel,omitempty"`
	UpdateTime int64                                  `protobuf:"varint,7,opt,name=updateTime" json:"updateTime,omitempty"`
}

func (m *PB_AccountLoginHistory) Reset()                    { *m = PB_AccountLoginHistory{} }
func (m *PB_AccountLoginHistory) String() string            { return proto.CompactTextString(m) }
func (*PB_AccountLoginHistory) ProtoMessage()               {}
func (*PB_AccountLoginHistory) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// HTTP头数据：opcode:消息号  sessionId:会话ID
// 玩家登陆 CS11001（第三方登陆或本地测试登陆都使用该协议）
type CS11001 struct {
	PB_PackType    int32                   `protobuf:"varint,11001,opt,name=PB_PackType,json=pBPackType" json:"PB_PackType,omitempty"`
	PB_PackRetType int32                   `protobuf:"varint,11002,opt,name=PB_PackRetType,json=pBPackRetType" json:"PB_PackRetType,omitempty"`
	PlatformType   CS11001_PB_PlatformType `protobuf:"varint,1,opt,name=platformType,enum=PB_login.CS11001_PB_PlatformType" json:"platformType,omitempty"`
	// 账号信息
	PlatformAccountId string `protobuf:"bytes,2,opt,name=platformAccountId" json:"platformAccountId,omitempty"`
	AuthId            string `protobuf:"bytes,3,opt,name=authId" json:"authId,omitempty"`
	// 客户端硬件信息
	ClientType  string `protobuf:"bytes,4,opt,name=clientType" json:"clientType,omitempty"`
	Uuid        string `protobuf:"bytes,5,opt,name=uuid" json:"uuid,omitempty"`
	ChannelId   int32  `protobuf:"varint,6,opt,name=channelId" json:"channelId,omitempty"`
	AdChannelId int64  `protobuf:"varint,7,opt,name=adChannelId" json:"adChannelId,omitempty"`
}

func (m *CS11001) Reset()                    { *m = CS11001{} }
func (m *CS11001) String() string            { return proto.CompactTextString(m) }
func (*CS11001) ProtoMessage()               {}
func (*CS11001) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// 登陆返回 SC11002
type SC11002 struct {
	PB_PackRetType      int32                     `protobuf:"varint,11002,opt,name=PB_PackRetType,json=pBPackRetType" json:"PB_PackRetType,omitempty"`
	AccountId           int64                     `protobuf:"varint,1,opt,name=accountId" json:"accountId,omitempty"`
	SessionId           string                    `protobuf:"bytes,2,opt,name=sessionId" json:"sessionId,omitempty"`
	PlatformAccountId   string                    `protobuf:"bytes,3,opt,name=platformAccountId" json:"platformAccountId,omitempty"`
	PlatformAccountName string                    `protobuf:"bytes,4,opt,name=platformAccountName" json:"platformAccountName,omitempty"`
	AccessToken         string                    `protobuf:"bytes,5,opt,name=accessToken" json:"accessToken,omitempty"`
	LoginHistories      []*PB_AccountLoginHistory `protobuf:"bytes,6,rep,name=loginHistories" json:"loginHistories,omitempty"`
	ServerInfos         []*PB_ServerInfo          `protobuf:"bytes,7,rep,name=serverInfos" json:"serverInfos,omitempty"`
}

func (m *SC11002) Reset()                    { *m = SC11002{} }
func (m *SC11002) String() string            { return proto.CompactTextString(m) }
func (*SC11002) ProtoMessage()               {}
func (*SC11002) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SC11002) GetLoginHistories() []*PB_AccountLoginHistory {
	if m != nil {
		return m.LoginHistories
	}
	return nil
}

func (m *SC11002) GetServerInfos() []*PB_ServerInfo {
	if m != nil {
		return m.ServerInfos
	}
	return nil
}

func init() {
	proto.RegisterType((*PB_ServerInfo)(nil), "PB_login.PB_ServerInfo")
	proto.RegisterType((*PB_AccountLoginHistory)(nil), "PB_login.PB_AccountLoginHistory")
	proto.RegisterType((*CS11001)(nil), "PB_login.CS11001")
	proto.RegisterType((*SC11002)(nil), "PB_login.SC11002")
	proto.RegisterEnum("PB_login.PB_ServerInfo_PB_ServerStatus", PB_ServerInfo_PB_ServerStatus_name, PB_ServerInfo_PB_ServerStatus_value)
	proto.RegisterEnum("PB_login.PB_AccountLoginHistory_PB_LoginRoleTye", PB_AccountLoginHistory_PB_LoginRoleTye_name, PB_AccountLoginHistory_PB_LoginRoleTye_value)
	proto.RegisterEnum("PB_login.CS11001_PB_PlatformType", CS11001_PB_PlatformType_name, CS11001_PB_PlatformType_value)
}

func init() { proto.RegisterFile("PB_Login.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 635 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x94, 0xdd, 0x6a, 0xd4, 0x40,
	0x14, 0xc7, 0x9b, 0x4d, 0x77, 0xb3, 0x7b, 0xb6, 0xdd, 0xc6, 0x51, 0x6a, 0x90, 0x22, 0x31, 0xa0,
	0xee, 0x85, 0x2c, 0xdb, 0x15, 0x04, 0x6f, 0x14, 0x53, 0x84, 0x2e, 0x14, 0x09, 0xd9, 0xf6, 0x7a,
	0x99, 0x26, 0xd3, 0x36, 0x34, 0x99, 0x09, 0xc9, 0xa4, 0xa5, 0xef, 0xe0, 0x13, 0xf8, 0x32, 0xbe,
	0x94, 0x37, 0x7a, 0x25, 0xf3, 0x91, 0x8f, 0xd6, 0x56, 0xbd, 0x9b, 0xff, 0xff, 0x9c, 0x99, 0x9c,
	0xfc, 0xce, 0x99, 0x81, 0x49, 0xe0, 0xaf, 0x8f, 0xd8, 0x79, 0x42, 0x67, 0x79, 0xc1, 0x38, 0x43,
	0xc3, 0xc0, 0x5f, 0xa7, 0x42, 0x7b, 0xdf, 0x7a, 0xb0, 0x1d, 0xf8, 0xeb, 0x15, 0x29, 0xae, 0x48,
	0xb1, 0xa4, 0x67, 0x0c, 0x3d, 0x83, 0x61, 0xa9, 0x54, 0xec, 0x18, 0xae, 0x31, 0xed, 0x87, 0x8d,
	0x46, 0xcf, 0x01, 0xd4, 0xfa, 0x0b, 0xce, 0x88, 0xd3, 0x73, 0x8d, 0xe9, 0x28, 0xec, 0x38, 0x68,
	0x0f, 0x46, 0x4a, 0x9d, 0x14, 0xa9, 0x63, 0xca, 0x70, 0x6b, 0xa0, 0x27, 0xd0, 0xe7, 0x51, 0xbe,
	0xcc, 0x9d, 0x4d, 0x19, 0x51, 0x02, 0x39, 0x60, 0xf1, 0x28, 0x0f, 0x58, 0xc1, 0x9d, 0xbe, 0xf4,
	0x6b, 0x89, 0x3e, 0xc2, 0xa0, 0xe4, 0x98, 0x57, 0xa5, 0x33, 0x70, 0x8d, 0xe9, 0x64, 0xf1, 0x7a,
	0x56, 0x97, 0x3d, 0xbb, 0x55, 0x72, 0xab, 0x56, 0x32, 0x3d, 0xd4, 0xdb, 0xbc, 0x0f, 0xb0, 0x73,
	0x27, 0x84, 0x86, 0xb0, 0x79, 0xce, 0x58, 0x6c, 0x6f, 0xa0, 0x11, 0xf4, 0xa3, 0x82, 0x5d, 0xc7,
	0xb6, 0x21, 0xcc, 0xd3, 0xaa, 0xbc, 0xb1, 0x7b, 0x68, 0x0b, 0x86, 0x19, 0x4e, 0x28, 0xc7, 0x09,
	0xb5, 0x4d, 0xef, 0x7b, 0x0f, 0x76, 0x03, 0x7f, 0xfd, 0x29, 0x8a, 0x58, 0x45, 0xb9, 0x04, 0x78,
	0x98, 0x94, 0x9c, 0x15, 0x37, 0x7f, 0xa5, 0x74, 0x04, 0xc3, 0x82, 0xa5, 0xe4, 0xf8, 0x26, 0x57,
	0x8c, 0x26, 0x8b, 0xf9, 0xad, 0xca, 0xef, 0x39, 0x6f, 0x56, 0x37, 0x28, 0x94, 0x1b, 0x49, 0xd8,
	0x9c, 0x20, 0xbe, 0x24, 0xd6, 0x92, 0xb8, 0x42, 0xda, 0x68, 0xc1, 0x5b, 0xac, 0x8f, 0xc8, 0x15,
	0x49, 0x25, 0xd5, 0x7e, 0xd8, 0x1a, 0xa2, 0x5b, 0xf8, 0x1a, 0x5f, 0xea, 0x70, 0x5f, 0x86, 0x3b,
	0x8e, 0x38, 0xf9, 0x2a, 0xc9, 0x55, 0x74, 0xa0, 0xfe, 0xa1, 0xd6, 0x62, 0x6f, 0x95, 0xc7, 0x98,
	0x93, 0xe3, 0x24, 0x23, 0x8e, 0xe5, 0x1a, 0x53, 0x33, 0xec, 0x38, 0xde, 0x4b, 0x89, 0xb6, 0x5b,
	0x32, 0xb2, 0xc0, 0xcc, 0x30, 0x55, 0x64, 0xaf, 0x59, 0x46, 0xa8, 0x6d, 0x78, 0x5f, 0x4d, 0xb0,
	0x0e, 0x56, 0xfb, 0xfb, 0xf3, 0xf9, 0x3e, 0x72, 0x61, 0x1c, 0xf8, 0xeb, 0x00, 0x47, 0x97, 0x92,
	0xcc, 0xcf, 0x13, 0x55, 0x50, 0xee, 0xd7, 0x16, 0x7a, 0x25, 0x07, 0x55, 0xc8, 0x90, 0x70, 0x99,
	0xf4, 0x4b, 0x25, 0x6d, 0xab, 0x24, 0xed, 0xa2, 0xcf, 0xb0, 0x95, 0xa7, 0x98, 0x9f, 0xb1, 0x22,
	0x93, 0x59, 0x86, 0x84, 0xfc, 0xa2, 0x85, 0xac, 0x3f, 0x29, 0x8c, 0xa0, 0x93, 0x18, 0xde, 0xda,
	0x86, 0xde, 0xc0, 0xa3, 0x5a, 0xeb, 0x96, 0x2c, 0x63, 0x3d, 0xd4, 0x7f, 0x06, 0xd0, 0x2e, 0x0c,
	0x70, 0xc5, 0x2f, 0x96, 0xb1, 0xee, 0x82, 0x56, 0x82, 0x54, 0x94, 0x26, 0x84, 0xaa, 0x82, 0xd5,
	0x68, 0x77, 0x1c, 0x84, 0x60, 0xb3, 0xaa, 0x92, 0x58, 0x0f, 0xb7, 0x5c, 0x8b, 0xbe, 0x45, 0x17,
	0x98, 0x52, 0x92, 0x2e, 0x63, 0x8d, 0xbe, 0x35, 0x04, 0x28, 0x1c, 0x1f, 0x34, 0x71, 0x05, 0xbf,
	0x6b, 0x79, 0xef, 0x24, 0xfd, 0xee, 0xaf, 0xa1, 0x1d, 0x18, 0xa7, 0x2c, 0xc2, 0xa9, 0x22, 0x60,
	0x6f, 0x20, 0x04, 0x93, 0xfa, 0x27, 0xb4, 0x67, 0x78, 0x3f, 0x7a, 0x60, 0xad, 0x0e, 0x04, 0x9b,
	0xc5, 0x7f, 0xc3, 0xde, 0x83, 0x11, 0x6e, 0xe8, 0x18, 0xb2, 0x96, 0xd6, 0x50, 0x37, 0xbe, 0x2c,
	0x13, 0x46, 0x1b, 0x76, 0xad, 0x71, 0x3f, 0x61, 0xf3, 0x21, 0xc2, 0x73, 0x78, 0x7c, 0xc7, 0x94,
	0x43, 0xaf, 0x90, 0xde, 0x17, 0x92, 0xa4, 0xa2, 0x88, 0x94, 0xe5, 0x31, 0xbb, 0x24, 0x54, 0x23,
	0xee, 0x5a, 0xe8, 0x10, 0x26, 0x69, 0x7b, 0xcf, 0x12, 0x22, 0xde, 0x12, 0x73, 0x3a, 0x5e, 0xb8,
	0xff, 0xba, 0x91, 0xe1, 0x9d, 0x7d, 0xe8, 0x3d, 0x8c, 0xcb, 0xe6, 0xc9, 0x29, 0x1d, 0x4b, 0x1e,
	0xf3, 0xf4, 0x81, 0x27, 0x29, 0xec, 0xe6, 0x9e, 0x0e, 0xe4, 0xab, 0xfb, 0xf6, 0x77, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xcd, 0x75, 0xc9, 0xd2, 0x87, 0x05, 0x00, 0x00,
}
