// Code generated by protoc-gen-go.
// source: message.proto
// DO NOT EDIT!

/*
Package pb_message is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	PB_CommonMsg
	SC10000
	PB_ServerInfo
	PB_AccountLoginHistory
	CS11001
	SC11002
*/
package pb_message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SC10000_PacketType int32

const (
	SC10000_PB_Temp        SC10000_PacketType = 0
	SC10000_PB_PackRetType SC10000_PacketType = 10000
)

var SC10000_PacketType_name = map[int32]string{
	0:     "PB_Temp",
	10000: "PB_PackRetType",
}
var SC10000_PacketType_value = map[string]int32{
	"PB_Temp":        0,
	"PB_PackRetType": 10000,
}

func (x SC10000_PacketType) Enum() *SC10000_PacketType {
	p := new(SC10000_PacketType)
	*p = x
	return p
}
func (x SC10000_PacketType) String() string {
	return proto.EnumName(SC10000_PacketType_name, int32(x))
}
func (x *SC10000_PacketType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SC10000_PacketType_value, data, "SC10000_PacketType")
	if err != nil {
		return err
	}
	*x = SC10000_PacketType(value)
	return nil
}
func (SC10000_PacketType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type SC10000ErrorCodeType int32

const (
	SC10000_PB_BuffPraseError SC10000ErrorCodeType = 0
	SC10000_PB_MsgPraseError  SC10000ErrorCodeType = 1
	SC10000_PB_MsgDealError   SC10000ErrorCodeType = 2
)

var SC10000ErrorCodeType_name = map[int32]string{
	0: "PB_BuffPraseError",
	1: "PB_MsgPraseError",
	2: "PB_MsgDealError",
}
var SC10000ErrorCodeType_value = map[string]int32{
	"PB_BuffPraseError": 0,
	"PB_MsgPraseError":  1,
	"PB_MsgDealError":   2,
}

func (x SC10000ErrorCodeType) Enum() *SC10000ErrorCodeType {
	p := new(SC10000ErrorCodeType)
	*p = x
	return p
}
func (x SC10000ErrorCodeType) String() string {
	return proto.EnumName(SC10000ErrorCodeType_name, int32(x))
}
func (x *SC10000ErrorCodeType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SC10000ErrorCodeType_value, data, "SC10000ErrorCodeType")
	if err != nil {
		return err
	}
	*x = SC10000ErrorCodeType(value)
	return nil
}
func (SC10000ErrorCodeType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 1} }

type PB_ServerInfo_PB_ServerStatus int32

const (
	PB_ServerInfo_good     PB_ServerInfo_PB_ServerStatus = 0
	PB_ServerInfo_crowd    PB_ServerInfo_PB_ServerStatus = 1
	PB_ServerInfo_busy     PB_ServerInfo_PB_ServerStatus = 2
	PB_ServerInfo_maintain PB_ServerInfo_PB_ServerStatus = 3
)

var PB_ServerInfo_PB_ServerStatus_name = map[int32]string{
	0: "good",
	1: "crowd",
	2: "busy",
	3: "maintain",
}
var PB_ServerInfo_PB_ServerStatus_value = map[string]int32{
	"good":     0,
	"crowd":    1,
	"busy":     2,
	"maintain": 3,
}

func (x PB_ServerInfo_PB_ServerStatus) Enum() *PB_ServerInfo_PB_ServerStatus {
	p := new(PB_ServerInfo_PB_ServerStatus)
	*p = x
	return p
}
func (x PB_ServerInfo_PB_ServerStatus) String() string {
	return proto.EnumName(PB_ServerInfo_PB_ServerStatus_name, int32(x))
}
func (x *PB_ServerInfo_PB_ServerStatus) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PB_ServerInfo_PB_ServerStatus_value, data, "PB_ServerInfo_PB_ServerStatus")
	if err != nil {
		return err
	}
	*x = PB_ServerInfo_PB_ServerStatus(value)
	return nil
}
func (PB_ServerInfo_PB_ServerStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{2, 0}
}

type PB_AccountLoginHistory_PB_LoginRoleTye int32

const (
	PB_AccountLoginHistory_man   PB_AccountLoginHistory_PB_LoginRoleTye = 0
	PB_AccountLoginHistory_women PB_AccountLoginHistory_PB_LoginRoleTye = 1
)

var PB_AccountLoginHistory_PB_LoginRoleTye_name = map[int32]string{
	0: "man",
	1: "women",
}
var PB_AccountLoginHistory_PB_LoginRoleTye_value = map[string]int32{
	"man":   0,
	"women": 1,
}

func (x PB_AccountLoginHistory_PB_LoginRoleTye) Enum() *PB_AccountLoginHistory_PB_LoginRoleTye {
	p := new(PB_AccountLoginHistory_PB_LoginRoleTye)
	*p = x
	return p
}
func (x PB_AccountLoginHistory_PB_LoginRoleTye) String() string {
	return proto.EnumName(PB_AccountLoginHistory_PB_LoginRoleTye_name, int32(x))
}
func (x *PB_AccountLoginHistory_PB_LoginRoleTye) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PB_AccountLoginHistory_PB_LoginRoleTye_value, data, "PB_AccountLoginHistory_PB_LoginRoleTye")
	if err != nil {
		return err
	}
	*x = PB_AccountLoginHistory_PB_LoginRoleTye(value)
	return nil
}
func (PB_AccountLoginHistory_PB_LoginRoleTye) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{3, 0}
}

type CS11001_PacketType int32

const (
	CS11001_PB_Temp        CS11001_PacketType = 0
	CS11001_PB_PackType    CS11001_PacketType = 11001
	CS11001_PB_PackRetType CS11001_PacketType = 11002
)

var CS11001_PacketType_name = map[int32]string{
	0:     "PB_Temp",
	11001: "PB_PackType",
	11002: "PB_PackRetType",
}
var CS11001_PacketType_value = map[string]int32{
	"PB_Temp":        0,
	"PB_PackType":    11001,
	"PB_PackRetType": 11002,
}

func (x CS11001_PacketType) Enum() *CS11001_PacketType {
	p := new(CS11001_PacketType)
	*p = x
	return p
}
func (x CS11001_PacketType) String() string {
	return proto.EnumName(CS11001_PacketType_name, int32(x))
}
func (x *CS11001_PacketType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CS11001_PacketType_value, data, "CS11001_PacketType")
	if err != nil {
		return err
	}
	*x = CS11001_PacketType(value)
	return nil
}
func (CS11001_PacketType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 0} }

type CS11001_PB_PlatformType int32

const (
	CS11001_local_login    CS11001_PB_PlatformType = 0
	CS11001_platform_login CS11001_PB_PlatformType = 1
)

var CS11001_PB_PlatformType_name = map[int32]string{
	0: "local_login",
	1: "platform_login",
}
var CS11001_PB_PlatformType_value = map[string]int32{
	"local_login":    0,
	"platform_login": 1,
}

func (x CS11001_PB_PlatformType) Enum() *CS11001_PB_PlatformType {
	p := new(CS11001_PB_PlatformType)
	*p = x
	return p
}
func (x CS11001_PB_PlatformType) String() string {
	return proto.EnumName(CS11001_PB_PlatformType_name, int32(x))
}
func (x *CS11001_PB_PlatformType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CS11001_PB_PlatformType_value, data, "CS11001_PB_PlatformType")
	if err != nil {
		return err
	}
	*x = CS11001_PB_PlatformType(value)
	return nil
}
func (CS11001_PB_PlatformType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 1} }

type SC11002_PacketType int32

const (
	SC11002_PB_Temp     SC11002_PacketType = 0
	SC11002_PB_PackType SC11002_PacketType = 10001
)

var SC11002_PacketType_name = map[int32]string{
	0:     "PB_Temp",
	10001: "PB_PackType",
}
var SC11002_PacketType_value = map[string]int32{
	"PB_Temp":     0,
	"PB_PackType": 10001,
}

func (x SC11002_PacketType) Enum() *SC11002_PacketType {
	p := new(SC11002_PacketType)
	*p = x
	return p
}
func (x SC11002_PacketType) String() string {
	return proto.EnumName(SC11002_PacketType_name, int32(x))
}
func (x *SC11002_PacketType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SC11002_PacketType_value, data, "SC11002_PacketType")
	if err != nil {
		return err
	}
	*x = SC11002_PacketType(value)
	return nil
}
func (SC11002_PacketType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 0} }

// //////////////////////////////////////////////通用协议///////////////////////////////////
// 通用消息包
type PB_CommonMsg struct {
	MsgId            *int32 `protobuf:"varint,1,opt,name=msgId" json:"msgId,omitempty"`
	OpCode           *int32 `protobuf:"varint,2,opt,name=opCode" json:"opCode,omitempty"`
	MsgBuf           []byte `protobuf:"bytes,3,opt,name=msgBuf" json:"msgBuf,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PB_CommonMsg) Reset()                    { *m = PB_CommonMsg{} }
func (m *PB_CommonMsg) String() string            { return proto.CompactTextString(m) }
func (*PB_CommonMsg) ProtoMessage()               {}
func (*PB_CommonMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PB_CommonMsg) GetMsgId() int32 {
	if m != nil && m.MsgId != nil {
		return *m.MsgId
	}
	return 0
}

func (m *PB_CommonMsg) GetOpCode() int32 {
	if m != nil && m.OpCode != nil {
		return *m.OpCode
	}
	return 0
}

func (m *PB_CommonMsg) GetMsgBuf() []byte {
	if m != nil {
		return m.MsgBuf
	}
	return nil
}

// 通用错误返回
type SC10000 struct {
	ErrorMsg         *string               `protobuf:"bytes,1,opt,name=errorMsg" json:"errorMsg,omitempty"`
	CsOpcode         *int32                `protobuf:"varint,2,opt,name=csOpcode" json:"csOpcode,omitempty"`
	ErrorCode        *SC10000ErrorCodeType `protobuf:"varint,3,opt,name=errorCode,enum=pb_message.SC10000ErrorCodeType" json:"errorCode,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *SC10000) Reset()                    { *m = SC10000{} }
func (m *SC10000) String() string            { return proto.CompactTextString(m) }
func (*SC10000) ProtoMessage()               {}
func (*SC10000) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SC10000) GetErrorMsg() string {
	if m != nil && m.ErrorMsg != nil {
		return *m.ErrorMsg
	}
	return ""
}

func (m *SC10000) GetCsOpcode() int32 {
	if m != nil && m.CsOpcode != nil {
		return *m.CsOpcode
	}
	return 0
}

func (m *SC10000) GetErrorCode() SC10000ErrorCodeType {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return SC10000_PB_BuffPraseError
}

type PB_ServerInfo struct {
	ServerId         *int32                         `protobuf:"varint,1,opt,name=serverId" json:"serverId,omitempty"`
	ServerName       *string                        `protobuf:"bytes,2,opt,name=serverName" json:"serverName,omitempty"`
	ServerUrl        *string                        `protobuf:"bytes,3,opt,name=serverUrl" json:"serverUrl,omitempty"`
	Status           *PB_ServerInfo_PB_ServerStatus `protobuf:"varint,4,opt,name=status,enum=pb_message.PB_ServerInfo_PB_ServerStatus" json:"status,omitempty"`
	XXX_unrecognized []byte                         `json:"-"`
}

func (m *PB_ServerInfo) Reset()                    { *m = PB_ServerInfo{} }
func (m *PB_ServerInfo) String() string            { return proto.CompactTextString(m) }
func (*PB_ServerInfo) ProtoMessage()               {}
func (*PB_ServerInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PB_ServerInfo) GetServerId() int32 {
	if m != nil && m.ServerId != nil {
		return *m.ServerId
	}
	return 0
}

func (m *PB_ServerInfo) GetServerName() string {
	if m != nil && m.ServerName != nil {
		return *m.ServerName
	}
	return ""
}

func (m *PB_ServerInfo) GetServerUrl() string {
	if m != nil && m.ServerUrl != nil {
		return *m.ServerUrl
	}
	return ""
}

func (m *PB_ServerInfo) GetStatus() PB_ServerInfo_PB_ServerStatus {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return PB_ServerInfo_good
}

type PB_AccountLoginHistory struct {
	ServerId         *int32                                  `protobuf:"varint,1,opt,name=serverId" json:"serverId,omitempty"`
	RoleType         *PB_AccountLoginHistory_PB_LoginRoleTye `protobuf:"varint,2,opt,name=roleType,enum=pb_message.PB_AccountLoginHistory_PB_LoginRoleTye" json:"roleType,omitempty"`
	RoleName         *string                                 `protobuf:"bytes,3,opt,name=roleName" json:"roleName,omitempty"`
	RoleLevel        *int32                                  `protobuf:"varint,4,opt,name=roleLevel" json:"roleLevel,omitempty"`
	AwakeLevel       *int32                                  `protobuf:"varint,5,opt,name=awakeLevel" json:"awakeLevel,omitempty"`
	VipLevel         *int32                                  `protobuf:"varint,6,opt,name=vipLevel" json:"vipLevel,omitempty"`
	UpdateTime       *int64                                  `protobuf:"varint,7,opt,name=updateTime" json:"updateTime,omitempty"`
	XXX_unrecognized []byte                                  `json:"-"`
}

func (m *PB_AccountLoginHistory) Reset()                    { *m = PB_AccountLoginHistory{} }
func (m *PB_AccountLoginHistory) String() string            { return proto.CompactTextString(m) }
func (*PB_AccountLoginHistory) ProtoMessage()               {}
func (*PB_AccountLoginHistory) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PB_AccountLoginHistory) GetServerId() int32 {
	if m != nil && m.ServerId != nil {
		return *m.ServerId
	}
	return 0
}

func (m *PB_AccountLoginHistory) GetRoleType() PB_AccountLoginHistory_PB_LoginRoleTye {
	if m != nil && m.RoleType != nil {
		return *m.RoleType
	}
	return PB_AccountLoginHistory_man
}

func (m *PB_AccountLoginHistory) GetRoleName() string {
	if m != nil && m.RoleName != nil {
		return *m.RoleName
	}
	return ""
}

func (m *PB_AccountLoginHistory) GetRoleLevel() int32 {
	if m != nil && m.RoleLevel != nil {
		return *m.RoleLevel
	}
	return 0
}

func (m *PB_AccountLoginHistory) GetAwakeLevel() int32 {
	if m != nil && m.AwakeLevel != nil {
		return *m.AwakeLevel
	}
	return 0
}

func (m *PB_AccountLoginHistory) GetVipLevel() int32 {
	if m != nil && m.VipLevel != nil {
		return *m.VipLevel
	}
	return 0
}

func (m *PB_AccountLoginHistory) GetUpdateTime() int64 {
	if m != nil && m.UpdateTime != nil {
		return *m.UpdateTime
	}
	return 0
}

// HTTP头数据：opcode:消息号  sessionId:会话ID
// 玩家登陆 CS11001（第三方登陆或本地测试登陆都使用该协议）
type CS11001 struct {
	PlatformType *CS11001_PB_PlatformType `protobuf:"varint,1,opt,name=platformType,enum=pb_message.CS11001_PB_PlatformType" json:"platformType,omitempty"`
	// 账号信息
	PlatformAccountId *string `protobuf:"bytes,2,opt,name=platformAccountId" json:"platformAccountId,omitempty"`
	AuthId            *string `protobuf:"bytes,3,opt,name=authId" json:"authId,omitempty"`
	// 客户端硬件信息
	ClientType       *string `protobuf:"bytes,4,opt,name=clientType" json:"clientType,omitempty"`
	Uuid             *string `protobuf:"bytes,5,opt,name=uuid" json:"uuid,omitempty"`
	ChannelId        *int32  `protobuf:"varint,6,opt,name=channelId" json:"channelId,omitempty"`
	AdChannelId      *int64  `protobuf:"varint,7,opt,name=adChannelId" json:"adChannelId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CS11001) Reset()                    { *m = CS11001{} }
func (m *CS11001) String() string            { return proto.CompactTextString(m) }
func (*CS11001) ProtoMessage()               {}
func (*CS11001) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CS11001) GetPlatformType() CS11001_PB_PlatformType {
	if m != nil && m.PlatformType != nil {
		return *m.PlatformType
	}
	return CS11001_local_login
}

func (m *CS11001) GetPlatformAccountId() string {
	if m != nil && m.PlatformAccountId != nil {
		return *m.PlatformAccountId
	}
	return ""
}

func (m *CS11001) GetAuthId() string {
	if m != nil && m.AuthId != nil {
		return *m.AuthId
	}
	return ""
}

func (m *CS11001) GetClientType() string {
	if m != nil && m.ClientType != nil {
		return *m.ClientType
	}
	return ""
}

func (m *CS11001) GetUuid() string {
	if m != nil && m.Uuid != nil {
		return *m.Uuid
	}
	return ""
}

func (m *CS11001) GetChannelId() int32 {
	if m != nil && m.ChannelId != nil {
		return *m.ChannelId
	}
	return 0
}

func (m *CS11001) GetAdChannelId() int64 {
	if m != nil && m.AdChannelId != nil {
		return *m.AdChannelId
	}
	return 0
}

// 登陆返回 SC11002
type SC11002 struct {
	SessionId           *string                   `protobuf:"bytes,1,opt,name=sessionId" json:"sessionId,omitempty"`
	LocalPlayerId       *int64                    `protobuf:"varint,2,opt,name=localPlayerId" json:"localPlayerId,omitempty"`
	PlatformAccountId   *string                   `protobuf:"bytes,3,opt,name=platformAccountId" json:"platformAccountId,omitempty"`
	PlatformAccountName *string                   `protobuf:"bytes,4,opt,name=platformAccountName" json:"platformAccountName,omitempty"`
	AccessToken         *string                   `protobuf:"bytes,5,opt,name=accessToken" json:"accessToken,omitempty"`
	LoginHistories      []*PB_AccountLoginHistory `protobuf:"bytes,6,rep,name=loginHistories" json:"loginHistories,omitempty"`
	ServerInfos         []*PB_ServerInfo          `protobuf:"bytes,7,rep,name=serverInfos" json:"serverInfos,omitempty"`
	XXX_unrecognized    []byte                    `json:"-"`
}

func (m *SC11002) Reset()                    { *m = SC11002{} }
func (m *SC11002) String() string            { return proto.CompactTextString(m) }
func (*SC11002) ProtoMessage()               {}
func (*SC11002) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *SC11002) GetSessionId() string {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return ""
}

func (m *SC11002) GetLocalPlayerId() int64 {
	if m != nil && m.LocalPlayerId != nil {
		return *m.LocalPlayerId
	}
	return 0
}

func (m *SC11002) GetPlatformAccountId() string {
	if m != nil && m.PlatformAccountId != nil {
		return *m.PlatformAccountId
	}
	return ""
}

func (m *SC11002) GetPlatformAccountName() string {
	if m != nil && m.PlatformAccountName != nil {
		return *m.PlatformAccountName
	}
	return ""
}

func (m *SC11002) GetAccessToken() string {
	if m != nil && m.AccessToken != nil {
		return *m.AccessToken
	}
	return ""
}

func (m *SC11002) GetLoginHistories() []*PB_AccountLoginHistory {
	if m != nil {
		return m.LoginHistories
	}
	return nil
}

func (m *SC11002) GetServerInfos() []*PB_ServerInfo {
	if m != nil {
		return m.ServerInfos
	}
	return nil
}

func init() {
	proto.RegisterType((*PB_CommonMsg)(nil), "pb_message.PB_CommonMsg")
	proto.RegisterType((*SC10000)(nil), "pb_message.SC10000")
	proto.RegisterType((*PB_ServerInfo)(nil), "pb_message.PB_ServerInfo")
	proto.RegisterType((*PB_AccountLoginHistory)(nil), "pb_message.PB_AccountLoginHistory")
	proto.RegisterType((*CS11001)(nil), "pb_message.CS11001")
	proto.RegisterType((*SC11002)(nil), "pb_message.SC11002")
	proto.RegisterEnum("pb_message.SC10000_PacketType", SC10000_PacketType_name, SC10000_PacketType_value)
	proto.RegisterEnum("pb_message.SC10000ErrorCodeType", SC10000ErrorCodeType_name, SC10000ErrorCodeType_value)
	proto.RegisterEnum("pb_message.PB_ServerInfo_PB_ServerStatus", PB_ServerInfo_PB_ServerStatus_name, PB_ServerInfo_PB_ServerStatus_value)
	proto.RegisterEnum("pb_message.PB_AccountLoginHistory_PB_LoginRoleTye", PB_AccountLoginHistory_PB_LoginRoleTye_name, PB_AccountLoginHistory_PB_LoginRoleTye_value)
	proto.RegisterEnum("pb_message.CS11001_PacketType", CS11001_PacketType_name, CS11001_PacketType_value)
	proto.RegisterEnum("pb_message.CS11001_PB_PlatformType", CS11001_PB_PlatformType_name, CS11001_PB_PlatformType_value)
	proto.RegisterEnum("pb_message.SC11002_PacketType", SC11002_PacketType_name, SC11002_PacketType_value)
}

func init() { proto.RegisterFile("message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 782 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x94, 0x51, 0x6f, 0xe3, 0x44,
	0x10, 0xc7, 0xeb, 0xb8, 0x69, 0xea, 0x49, 0x9b, 0xf3, 0x6d, 0x8f, 0x53, 0x40, 0x08, 0x05, 0x03,
	0x52, 0x11, 0x28, 0x72, 0xf2, 0xc0, 0x0b, 0x12, 0x70, 0x0e, 0x08, 0x82, 0xae, 0xc5, 0x6c, 0xd3,
	0x67, 0x6b, 0xcf, 0xde, 0xf8, 0xac, 0xda, 0x5e, 0xcb, 0x6b, 0xb7, 0xea, 0x07, 0x28, 0xcf, 0xf0,
	0x91, 0xf8, 0x3e, 0x7c, 0x01, 0x78, 0x42, 0x3b, 0xde, 0xda, 0x6e, 0x49, 0x81, 0xb7, 0xfd, 0xff,
	0x67, 0x67, 0xbc, 0xf3, 0xdb, 0x1d, 0xc3, 0x71, 0xc6, 0xa5, 0x64, 0x31, 0x9f, 0x17, 0xa5, 0xa8,
	0x04, 0x81, 0xe2, 0x4d, 0xa0, 0x1d, 0x67, 0x03, 0x47, 0xbe, 0x17, 0xac, 0x44, 0x96, 0x89, 0xfc,
	0x4c, 0xc6, 0xe4, 0x05, 0x0c, 0x33, 0x19, 0xaf, 0xa3, 0xa9, 0x31, 0x33, 0x4e, 0x87, 0xb4, 0x11,
	0xe4, 0x25, 0x1c, 0x88, 0x62, 0x25, 0x22, 0x3e, 0x1d, 0xa0, 0xad, 0x95, 0xf2, 0x33, 0x19, 0x7b,
	0xf5, 0x76, 0x6a, 0xce, 0x8c, 0xd3, 0x23, 0xaa, 0x95, 0x73, 0x37, 0x80, 0xd1, 0xc5, 0x6a, 0xe1,
	0xba, 0xae, 0x4b, 0xde, 0x83, 0x43, 0x5e, 0x96, 0xa2, 0x3c, 0x93, 0x31, 0x16, 0xb5, 0x68, 0xab,
	0x55, 0x2c, 0x94, 0x3f, 0x15, 0x61, 0x57, 0xb9, 0xd5, 0xe4, 0x6b, 0xb0, 0x70, 0x1f, 0x7e, 0x56,
	0x95, 0x9f, 0x2c, 0x3f, 0x9c, 0x77, 0x27, 0x9f, 0xeb, 0xfa, 0xf3, 0x76, 0xd3, 0xe6, 0xb6, 0xe0,
	0xb4, 0xcb, 0x71, 0xe6, 0x00, 0x3e, 0x0b, 0xaf, 0x78, 0xa5, 0x02, 0x64, 0x0c, 0x23, 0xdf, 0x0b,
	0x36, 0x3c, 0x2b, 0xec, 0x3d, 0x72, 0x02, 0x13, 0xdf, 0x0b, 0x54, 0x94, 0x36, 0x61, 0xfb, 0xd7,
	0x73, 0xe7, 0x67, 0x38, 0x7e, 0x50, 0x8b, 0xbc, 0x03, 0xcf, 0x7d, 0x2f, 0xf0, 0xea, 0xed, 0xd6,
	0x2f, 0x99, 0xe4, 0xdf, 0xa9, 0xa0, 0xbd, 0x47, 0x5e, 0x80, 0xed, 0x7b, 0xc1, 0x99, 0x8c, 0x7b,
	0xae, 0x41, 0x4e, 0xe0, 0x59, 0xe3, 0x7e, 0xcb, 0x59, 0xda, 0x98, 0x03, 0xe7, 0x0f, 0x03, 0x8e,
	0x7d, 0x2f, 0xb8, 0xe0, 0xe5, 0x35, 0x2f, 0xd7, 0xf9, 0x56, 0xa8, 0x8e, 0x65, 0xa3, 0xee, 0x11,
	0xb7, 0x9a, 0x7c, 0x00, 0xd0, 0xac, 0xcf, 0x59, 0xd6, 0xf0, 0xb0, 0x68, 0xcf, 0x21, 0xef, 0x83,
	0xd5, 0xa8, 0xcb, 0x32, 0x45, 0x22, 0x16, 0xed, 0x0c, 0xf2, 0x0a, 0x0e, 0x64, 0xc5, 0xaa, 0x5a,
	0x4e, 0xf7, 0x11, 0xd6, 0xa7, 0x7d, 0x58, 0x0f, 0x0e, 0xd1, 0xa9, 0x0b, 0x4c, 0xa0, 0x3a, 0xd1,
	0xf9, 0x0a, 0x7b, 0xe8, 0x87, 0xc8, 0x21, 0xec, 0xc7, 0x42, 0x44, 0xf6, 0x1e, 0xb1, 0x60, 0x18,
	0x96, 0xe2, 0x26, 0xb2, 0x0d, 0x65, 0xbe, 0xa9, 0xe5, 0xad, 0x3d, 0x20, 0x47, 0x70, 0x98, 0xb1,
	0x24, 0xaf, 0x58, 0x92, 0xdb, 0xa6, 0xf3, 0xfb, 0x00, 0x5e, 0xfa, 0x5e, 0xf0, 0x2a, 0x0c, 0x45,
	0x9d, 0x57, 0xaf, 0x45, 0x9c, 0xe4, 0x3f, 0x24, 0xb2, 0x12, 0xe5, 0xed, 0xbf, 0xf6, 0x7d, 0x0e,
	0x87, 0xa5, 0x48, 0x91, 0x39, 0x76, 0x3d, 0x59, 0x2e, 0x1f, 0x9d, 0x7d, 0x47, 0x45, 0x65, 0xa3,
	0xa6, 0x98, 0xca, 0x69, 0x5b, 0x43, 0x7d, 0x4b, 0xad, 0x91, 0x62, 0x83, 0xa9, 0xd5, 0x8a, 0xa1,
	0x5a, 0xbf, 0xe6, 0xd7, 0x3c, 0x45, 0x50, 0x43, 0xda, 0x19, 0xea, 0x06, 0xd8, 0x0d, 0xbb, 0xd2,
	0xe1, 0x21, 0x86, 0x7b, 0x8e, 0xaa, 0x7c, 0x9d, 0x14, 0x4d, 0xf4, 0xa0, 0xe9, 0xe2, 0x5e, 0xab,
	0xdc, 0xba, 0x88, 0x58, 0xc5, 0x37, 0x49, 0xc6, 0xa7, 0xa3, 0x99, 0x71, 0x6a, 0xd2, 0x9e, 0xe3,
	0x7c, 0x82, 0x70, 0xfb, 0x47, 0x26, 0x23, 0x30, 0x33, 0x96, 0x37, 0x6c, 0x6f, 0x44, 0xc6, 0x73,
	0xdb, 0x70, 0x7e, 0x31, 0x61, 0xb4, 0xba, 0x58, 0x2c, 0x5c, 0x77, 0x41, 0xbe, 0x87, 0xa3, 0x22,
	0x65, 0xd5, 0x56, 0x94, 0x19, 0xc2, 0x31, 0x10, 0xce, 0x47, 0x7d, 0x38, 0x7a, 0xab, 0xa2, 0xe1,
	0xf7, 0xb6, 0xd2, 0x07, 0x89, 0xe4, 0x73, 0x78, 0x7e, 0xaf, 0x35, 0xca, 0x75, 0xa4, 0x1f, 0xd8,
	0x3f, 0x03, 0x6a, 0xaa, 0x59, 0x5d, 0xbd, 0x5d, 0x47, 0x9a, 0x9e, 0x56, 0xaa, 0xc3, 0x30, 0x4d,
	0x78, 0x8e, 0x13, 0x83, 0xf0, 0x2c, 0xda, 0x73, 0x08, 0x81, 0xfd, 0xba, 0x4e, 0x22, 0xe4, 0x66,
	0x51, 0x5c, 0x2b, 0xde, 0xe1, 0x5b, 0x96, 0xe7, 0x3c, 0x5d, 0x47, 0x1a, 0x59, 0x67, 0x90, 0x19,
	0x8c, 0x59, 0xb4, 0x6a, 0xe3, 0x0d, 0xb4, 0xbe, 0xe5, 0x7c, 0xf3, 0xf4, 0x10, 0xdb, 0x30, 0xd6,
	0x43, 0x8c, 0x13, 0xfc, 0xe7, 0xe5, 0x8e, 0xb1, 0xfe, 0xeb, 0xd2, 0xf9, 0x02, 0xb9, 0xf7, 0xe1,
	0x90, 0x67, 0x30, 0x4e, 0x45, 0xc8, 0xd2, 0x20, 0x55, 0xb7, 0x61, 0xef, 0x11, 0x02, 0x93, 0x7b,
	0x0c, 0xda, 0x33, 0x9c, 0x3b, 0x13, 0xff, 0x61, 0x0b, 0xd7, 0x5d, 0x36, 0x93, 0x27, 0x65, 0x22,
	0x72, 0xfd, 0x7c, 0x71, 0xf2, 0xb4, 0x41, 0x3e, 0x86, 0x63, 0x2c, 0xe7, 0xa7, 0xec, 0x16, 0x1f,
	0xf8, 0x00, 0xfb, 0x78, 0x68, 0xee, 0xbe, 0x03, 0xf3, 0xa9, 0x3b, 0x70, 0xe1, 0xe4, 0x91, 0x89,
	0xcf, 0xb9, 0x81, 0xbe, 0x2b, 0x84, 0x2c, 0xc3, 0x90, 0x4b, 0xb9, 0x11, 0x57, 0x3c, 0xd7, 0x97,
	0xd0, 0xb7, 0xc8, 0x8f, 0x30, 0x49, 0xbb, 0x09, 0x4a, 0xb8, 0x9c, 0x1e, 0xcc, 0xcc, 0xd3, 0xf1,
	0xd2, 0xf9, 0xef, 0x69, 0xa3, 0x8f, 0x32, 0xc9, 0x97, 0x30, 0x96, 0xed, 0x0f, 0x45, 0x4e, 0x47,
	0x58, 0xe8, 0xdd, 0x27, 0x7f, 0x39, 0xb4, 0xbf, 0xdb, 0xf9, 0xec, 0x7f, 0x5f, 0xea, 0x6f, 0xe7,
	0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0x8a, 0xdd, 0xa1, 0xe4, 0xbd, 0x06, 0x00, 0x00,
}
