/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.basemsg.PB_CommonMsg', null, global);
goog.exportSymbol('proto.basemsg.SC10000', null, global);
goog.exportSymbol('proto.basemsg.SC10000.PacketType', null, global);
goog.exportSymbol('proto.basemsg.SC10000.errorCodeType', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.basemsg.PB_CommonMsg = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.basemsg.PB_CommonMsg, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.basemsg.PB_CommonMsg.displayName = 'proto.basemsg.PB_CommonMsg';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.basemsg.PB_CommonMsg.prototype.toObject = function(opt_includeInstance) {
  return proto.basemsg.PB_CommonMsg.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.basemsg.PB_CommonMsg} msg The msg instance to transform.
 * @return {!Object}
 */
proto.basemsg.PB_CommonMsg.toObject = function(includeInstance, msg) {
  var f, obj = {
    msgid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    opcode: jspb.Message.getFieldWithDefault(msg, 2, 0),
    msgbuf: msg.getMsgbuf_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.basemsg.PB_CommonMsg}
 */
proto.basemsg.PB_CommonMsg.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.basemsg.PB_CommonMsg;
  return proto.basemsg.PB_CommonMsg.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.basemsg.PB_CommonMsg} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.basemsg.PB_CommonMsg}
 */
proto.basemsg.PB_CommonMsg.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMsgid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setOpcode(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setMsgbuf(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.basemsg.PB_CommonMsg} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.basemsg.PB_CommonMsg.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.basemsg.PB_CommonMsg.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.basemsg.PB_CommonMsg.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getMsgid();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = this.getOpcode();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = this.getMsgbuf_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      3,
      f
    );
  }
};


/**
 * optional int32 msgId = 1;
 * @return {number}
 */
proto.basemsg.PB_CommonMsg.prototype.getMsgid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.basemsg.PB_CommonMsg.prototype.setMsgid = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional int32 opCode = 2;
 * @return {number}
 */
proto.basemsg.PB_CommonMsg.prototype.getOpcode = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.basemsg.PB_CommonMsg.prototype.setOpcode = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional bytes msgBuf = 3;
 * @return {!(string|Uint8Array)}
 */
proto.basemsg.PB_CommonMsg.prototype.getMsgbuf = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes msgBuf = 3;
 * This is a type-conversion wrapper around `getMsgbuf()`
 * @return {string}
 */
proto.basemsg.PB_CommonMsg.prototype.getMsgbuf_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getMsgbuf()));
};


/**
 * optional bytes msgBuf = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getMsgbuf()`
 * @return {!Uint8Array}
 */
proto.basemsg.PB_CommonMsg.prototype.getMsgbuf_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getMsgbuf()));
};


/** @param {!(string|Uint8Array)} value */
proto.basemsg.PB_CommonMsg.prototype.setMsgbuf = function(value) {
  jspb.Message.setField(this, 3, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.basemsg.SC10000 = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.basemsg.SC10000, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.basemsg.SC10000.displayName = 'proto.basemsg.SC10000';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.basemsg.SC10000.prototype.toObject = function(opt_includeInstance) {
  return proto.basemsg.SC10000.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.basemsg.SC10000} msg The msg instance to transform.
 * @return {!Object}
 */
proto.basemsg.SC10000.toObject = function(includeInstance, msg) {
  var f, obj = {
    errormsg: jspb.Message.getFieldWithDefault(msg, 1, ""),
    csopcode: jspb.Message.getFieldWithDefault(msg, 2, 0),
    errorcode: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.basemsg.SC10000}
 */
proto.basemsg.SC10000.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.basemsg.SC10000;
  return proto.basemsg.SC10000.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.basemsg.SC10000} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.basemsg.SC10000}
 */
proto.basemsg.SC10000.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setErrormsg(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCsopcode(value);
      break;
    case 3:
      var value = /** @type {!proto.basemsg.SC10000.errorCodeType} */ (reader.readEnum());
      msg.setErrorcode(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.basemsg.SC10000} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.basemsg.SC10000.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.basemsg.SC10000.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.basemsg.SC10000.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getErrormsg();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = this.getCsopcode();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = this.getErrorcode();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
};


/**
 * optional string errorMsg = 1;
 * @return {string}
 */
proto.basemsg.SC10000.prototype.getErrormsg = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.basemsg.SC10000.prototype.setErrormsg = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional int32 csOpcode = 2;
 * @return {number}
 */
proto.basemsg.SC10000.prototype.getCsopcode = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.basemsg.SC10000.prototype.setCsopcode = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional errorCodeType errorCode = 3;
 * @return {!proto.basemsg.SC10000.errorCodeType}
 */
proto.basemsg.SC10000.prototype.getErrorcode = function() {
  return /** @type {!proto.basemsg.SC10000.errorCodeType} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {!proto.basemsg.SC10000.errorCodeType} value */
proto.basemsg.SC10000.prototype.setErrorcode = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * @enum {number}
 */
proto.basemsg.SC10000.PacketType = {
  PB_TEMP: 0,
  PB_PACKRETTYPE: 10000
};

/**
 * @enum {number}
 */
proto.basemsg.SC10000.errorCodeType = {
  PB_BUFFPRASEERROR: 0,
  PB_MSGPRASEERROR: 1,
  PB_MSGDEALERROR: 2
};

goog.object.extend(exports, proto.basemsg);
