/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.pb_message.CS11001', null, global);
goog.exportSymbol('proto.pb_message.CS11001.PB_PlatformType', null, global);
goog.exportSymbol('proto.pb_message.CS11001.PacketType', null, global);
goog.exportSymbol('proto.pb_message.PB_AccountLoginHistory', null, global);
goog.exportSymbol('proto.pb_message.PB_AccountLoginHistory.PB_LoginRoleTye', null, global);
goog.exportSymbol('proto.pb_message.PB_CommonMsg', null, global);
goog.exportSymbol('proto.pb_message.PB_ServerInfo', null, global);
goog.exportSymbol('proto.pb_message.PB_ServerInfo.PB_ServerStatus', null, global);
goog.exportSymbol('proto.pb_message.SC10000', null, global);
goog.exportSymbol('proto.pb_message.SC10000.PacketType', null, global);
goog.exportSymbol('proto.pb_message.SC10000.errorCodeType', null, global);
goog.exportSymbol('proto.pb_message.SC11002', null, global);
goog.exportSymbol('proto.pb_message.SC11002.PacketType', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pb_message.PB_CommonMsg = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pb_message.PB_CommonMsg, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.pb_message.PB_CommonMsg.displayName = 'proto.pb_message.PB_CommonMsg';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pb_message.PB_CommonMsg.prototype.toObject = function(opt_includeInstance) {
  return proto.pb_message.PB_CommonMsg.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pb_message.PB_CommonMsg} msg The msg instance to transform.
 * @return {!Object}
 */
proto.pb_message.PB_CommonMsg.toObject = function(includeInstance, msg) {
  var f, obj = {
    msgid: jspb.Message.getField(msg, 1),
    opcode: jspb.Message.getField(msg, 2),
    msgbuf: msg.getMsgbuf_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pb_message.PB_CommonMsg}
 */
proto.pb_message.PB_CommonMsg.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pb_message.PB_CommonMsg;
  return proto.pb_message.PB_CommonMsg.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pb_message.PB_CommonMsg} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pb_message.PB_CommonMsg}
 */
proto.pb_message.PB_CommonMsg.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMsgid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setOpcode(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setMsgbuf(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.pb_message.PB_CommonMsg} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.pb_message.PB_CommonMsg.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pb_message.PB_CommonMsg.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.pb_message.PB_CommonMsg.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = jspb.Message.getField(this, 1);
  if (f != null) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = jspb.Message.getField(this, 2);
  if (f != null) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = jspb.Message.getField(this, 3);
  if (f != null) {
    writer.writeBytes(
      3,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.pb_message.PB_CommonMsg} The clone.
 */
proto.pb_message.PB_CommonMsg.prototype.cloneMessage = function() {
  return /** @type {!proto.pb_message.PB_CommonMsg} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional int32 msgId = 1;
 * @return {number}
 */
proto.pb_message.PB_CommonMsg.prototype.getMsgid = function() {
  return /** @type {number} */ (!this.hasMsgid() ? 0 : jspb.Message.getField(this, 1));
};


/** @param {number?|undefined} value  */
proto.pb_message.PB_CommonMsg.prototype.setMsgid = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.pb_message.PB_CommonMsg.prototype.clearMsgid = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.pb_message.PB_CommonMsg.prototype.hasMsgid = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int32 opCode = 2;
 * @return {number}
 */
proto.pb_message.PB_CommonMsg.prototype.getOpcode = function() {
  return /** @type {number} */ (!this.hasOpcode() ? 0 : jspb.Message.getField(this, 2));
};


/** @param {number?|undefined} value  */
proto.pb_message.PB_CommonMsg.prototype.setOpcode = function(value) {
  jspb.Message.setField(this, 2, value);
};


proto.pb_message.PB_CommonMsg.prototype.clearOpcode = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.pb_message.PB_CommonMsg.prototype.hasOpcode = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional bytes msgBuf = 3;
 * @return {(string|Uint8Array)}
 */
proto.pb_message.PB_CommonMsg.prototype.getMsgbuf = function() {
  return /** @type {(string|Uint8Array)} */ (!this.hasMsgbuf() ? "" : jspb.Message.getField(this, 3));
};


/**
 * optional bytes msgBuf = 3;
 * This is a type-conversion wrapper around `getMsgbuf()`
 * @return {string}
 */
proto.pb_message.PB_CommonMsg.prototype.getMsgbuf_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getMsgbuf()));
};


/**
 * optional bytes msgBuf = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getMsgbuf()`
 * @return {Uint8Array}
 */
proto.pb_message.PB_CommonMsg.prototype.getMsgbuf_asU8 = function() {
  return /** @type {Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getMsgbuf()));
};


/** @param {(string|Uint8Array)|undefined} value  */
proto.pb_message.PB_CommonMsg.prototype.setMsgbuf = function(value) {
  jspb.Message.setField(this, 3, value);
};


proto.pb_message.PB_CommonMsg.prototype.clearMsgbuf = function() {
  jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.pb_message.PB_CommonMsg.prototype.hasMsgbuf = function() {
  return jspb.Message.getField(this, 3) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pb_message.SC10000 = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pb_message.SC10000, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.pb_message.SC10000.displayName = 'proto.pb_message.SC10000';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pb_message.SC10000.prototype.toObject = function(opt_includeInstance) {
  return proto.pb_message.SC10000.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pb_message.SC10000} msg The msg instance to transform.
 * @return {!Object}
 */
proto.pb_message.SC10000.toObject = function(includeInstance, msg) {
  var f, obj = {
    errormsg: jspb.Message.getField(msg, 1),
    csopcode: jspb.Message.getField(msg, 2),
    errorcode: jspb.Message.getField(msg, 3)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pb_message.SC10000}
 */
proto.pb_message.SC10000.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pb_message.SC10000;
  return proto.pb_message.SC10000.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pb_message.SC10000} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pb_message.SC10000}
 */
proto.pb_message.SC10000.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setErrormsg(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCsopcode(value);
      break;
    case 3:
      var value = /** @type {!proto.pb_message.SC10000.errorCodeType} */ (reader.readEnum());
      msg.setErrorcode(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.pb_message.SC10000} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.pb_message.SC10000.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pb_message.SC10000.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.pb_message.SC10000.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = jspb.Message.getField(this, 1);
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = jspb.Message.getField(this, 2);
  if (f != null) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = jspb.Message.getField(this, 3);
  if (f != null) {
    writer.writeEnum(
      3,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.pb_message.SC10000} The clone.
 */
proto.pb_message.SC10000.prototype.cloneMessage = function() {
  return /** @type {!proto.pb_message.SC10000} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string errorMsg = 1;
 * @return {string}
 */
proto.pb_message.SC10000.prototype.getErrormsg = function() {
  return /** @type {string} */ (!this.hasErrormsg() ? "" : jspb.Message.getField(this, 1));
};


/** @param {string?|undefined} value  */
proto.pb_message.SC10000.prototype.setErrormsg = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.pb_message.SC10000.prototype.clearErrormsg = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.pb_message.SC10000.prototype.hasErrormsg = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int32 csOpcode = 2;
 * @return {number}
 */
proto.pb_message.SC10000.prototype.getCsopcode = function() {
  return /** @type {number} */ (!this.hasCsopcode() ? 0 : jspb.Message.getField(this, 2));
};


/** @param {number?|undefined} value  */
proto.pb_message.SC10000.prototype.setCsopcode = function(value) {
  jspb.Message.setField(this, 2, value);
};


proto.pb_message.SC10000.prototype.clearCsopcode = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.pb_message.SC10000.prototype.hasCsopcode = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional errorCodeType errorCode = 3;
 * @return {proto.pb_message.SC10000.errorCodeType}
 */
proto.pb_message.SC10000.prototype.getErrorcode = function() {
  return /** @type {proto.pb_message.SC10000.errorCodeType} */ (!this.hasErrorcode() ? 0 : jspb.Message.getField(this, 3));
};


/** @param {proto.pb_message.SC10000.errorCodeType|undefined} value  */
proto.pb_message.SC10000.prototype.setErrorcode = function(value) {
  jspb.Message.setField(this, 3, value);
};


proto.pb_message.SC10000.prototype.clearErrorcode = function() {
  jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.pb_message.SC10000.prototype.hasErrorcode = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * @enum {number}
 */
proto.pb_message.SC10000.PacketType = {
  PB_TEMP: 0,
  PB_PACKRETTYPE: 10000
};

/**
 * @enum {number}
 */
proto.pb_message.SC10000.errorCodeType = {
  PB_BUFFPRASEERROR: 0,
  PB_MSGPRASEERROR: 1,
  PB_MSGDEALERROR: 2
};


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pb_message.PB_ServerInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pb_message.PB_ServerInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.pb_message.PB_ServerInfo.displayName = 'proto.pb_message.PB_ServerInfo';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pb_message.PB_ServerInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.pb_message.PB_ServerInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pb_message.PB_ServerInfo} msg The msg instance to transform.
 * @return {!Object}
 */
proto.pb_message.PB_ServerInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    serverid: jspb.Message.getField(msg, 1),
    servername: jspb.Message.getField(msg, 2),
    serverurl: jspb.Message.getField(msg, 3),
    status: jspb.Message.getField(msg, 4)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pb_message.PB_ServerInfo}
 */
proto.pb_message.PB_ServerInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pb_message.PB_ServerInfo;
  return proto.pb_message.PB_ServerInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pb_message.PB_ServerInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pb_message.PB_ServerInfo}
 */
proto.pb_message.PB_ServerInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setServerid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setServername(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setServerurl(value);
      break;
    case 4:
      var value = /** @type {!proto.pb_message.PB_ServerInfo.PB_ServerStatus} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.pb_message.PB_ServerInfo} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.pb_message.PB_ServerInfo.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pb_message.PB_ServerInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.pb_message.PB_ServerInfo.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = jspb.Message.getField(this, 1);
  if (f != null) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = jspb.Message.getField(this, 2);
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = jspb.Message.getField(this, 3);
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
  f = jspb.Message.getField(this, 4);
  if (f != null) {
    writer.writeEnum(
      4,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.pb_message.PB_ServerInfo} The clone.
 */
proto.pb_message.PB_ServerInfo.prototype.cloneMessage = function() {
  return /** @type {!proto.pb_message.PB_ServerInfo} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional int32 serverId = 1;
 * @return {number}
 */
proto.pb_message.PB_ServerInfo.prototype.getServerid = function() {
  return /** @type {number} */ (!this.hasServerid() ? 0 : jspb.Message.getField(this, 1));
};


/** @param {number?|undefined} value  */
proto.pb_message.PB_ServerInfo.prototype.setServerid = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.pb_message.PB_ServerInfo.prototype.clearServerid = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.pb_message.PB_ServerInfo.prototype.hasServerid = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string serverName = 2;
 * @return {string}
 */
proto.pb_message.PB_ServerInfo.prototype.getServername = function() {
  return /** @type {string} */ (!this.hasServername() ? "" : jspb.Message.getField(this, 2));
};


/** @param {string?|undefined} value  */
proto.pb_message.PB_ServerInfo.prototype.setServername = function(value) {
  jspb.Message.setField(this, 2, value);
};


proto.pb_message.PB_ServerInfo.prototype.clearServername = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.pb_message.PB_ServerInfo.prototype.hasServername = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string serverUrl = 3;
 * @return {string}
 */
proto.pb_message.PB_ServerInfo.prototype.getServerurl = function() {
  return /** @type {string} */ (!this.hasServerurl() ? "" : jspb.Message.getField(this, 3));
};


/** @param {string?|undefined} value  */
proto.pb_message.PB_ServerInfo.prototype.setServerurl = function(value) {
  jspb.Message.setField(this, 3, value);
};


proto.pb_message.PB_ServerInfo.prototype.clearServerurl = function() {
  jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.pb_message.PB_ServerInfo.prototype.hasServerurl = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional PB_ServerStatus status = 4;
 * @return {proto.pb_message.PB_ServerInfo.PB_ServerStatus}
 */
proto.pb_message.PB_ServerInfo.prototype.getStatus = function() {
  return /** @type {proto.pb_message.PB_ServerInfo.PB_ServerStatus} */ (!this.hasStatus() ? 0 : jspb.Message.getField(this, 4));
};


/** @param {proto.pb_message.PB_ServerInfo.PB_ServerStatus|undefined} value  */
proto.pb_message.PB_ServerInfo.prototype.setStatus = function(value) {
  jspb.Message.setField(this, 4, value);
};


proto.pb_message.PB_ServerInfo.prototype.clearStatus = function() {
  jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.pb_message.PB_ServerInfo.prototype.hasStatus = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * @enum {number}
 */
proto.pb_message.PB_ServerInfo.PB_ServerStatus = {
  GOOD: 0,
  CROWD: 1,
  BUSY: 2,
  MAINTAIN: 3
};


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pb_message.PB_AccountLoginHistory = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pb_message.PB_AccountLoginHistory, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.pb_message.PB_AccountLoginHistory.displayName = 'proto.pb_message.PB_AccountLoginHistory';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pb_message.PB_AccountLoginHistory.prototype.toObject = function(opt_includeInstance) {
  return proto.pb_message.PB_AccountLoginHistory.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pb_message.PB_AccountLoginHistory} msg The msg instance to transform.
 * @return {!Object}
 */
proto.pb_message.PB_AccountLoginHistory.toObject = function(includeInstance, msg) {
  var f, obj = {
    serverid: jspb.Message.getField(msg, 1),
    roletype: jspb.Message.getField(msg, 2),
    rolename: jspb.Message.getField(msg, 3),
    rolelevel: jspb.Message.getField(msg, 4),
    awakelevel: jspb.Message.getField(msg, 5),
    viplevel: jspb.Message.getField(msg, 6),
    updatetime: jspb.Message.getField(msg, 7)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pb_message.PB_AccountLoginHistory}
 */
proto.pb_message.PB_AccountLoginHistory.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pb_message.PB_AccountLoginHistory;
  return proto.pb_message.PB_AccountLoginHistory.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pb_message.PB_AccountLoginHistory} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pb_message.PB_AccountLoginHistory}
 */
proto.pb_message.PB_AccountLoginHistory.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setServerid(value);
      break;
    case 2:
      var value = /** @type {!proto.pb_message.PB_AccountLoginHistory.PB_LoginRoleTye} */ (reader.readEnum());
      msg.setRoletype(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setRolename(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRolelevel(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAwakelevel(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setViplevel(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setUpdatetime(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.pb_message.PB_AccountLoginHistory} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.pb_message.PB_AccountLoginHistory.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pb_message.PB_AccountLoginHistory.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.pb_message.PB_AccountLoginHistory.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = jspb.Message.getField(this, 1);
  if (f != null) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = jspb.Message.getField(this, 2);
  if (f != null) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = jspb.Message.getField(this, 3);
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
  f = jspb.Message.getField(this, 4);
  if (f != null) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = jspb.Message.getField(this, 5);
  if (f != null) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = jspb.Message.getField(this, 6);
  if (f != null) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = jspb.Message.getField(this, 7);
  if (f != null) {
    writer.writeInt64(
      7,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.pb_message.PB_AccountLoginHistory} The clone.
 */
proto.pb_message.PB_AccountLoginHistory.prototype.cloneMessage = function() {
  return /** @type {!proto.pb_message.PB_AccountLoginHistory} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional int32 serverId = 1;
 * @return {number}
 */
proto.pb_message.PB_AccountLoginHistory.prototype.getServerid = function() {
  return /** @type {number} */ (!this.hasServerid() ? 0 : jspb.Message.getField(this, 1));
};


/** @param {number?|undefined} value  */
proto.pb_message.PB_AccountLoginHistory.prototype.setServerid = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.pb_message.PB_AccountLoginHistory.prototype.clearServerid = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.pb_message.PB_AccountLoginHistory.prototype.hasServerid = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional PB_LoginRoleTye roleType = 2;
 * @return {proto.pb_message.PB_AccountLoginHistory.PB_LoginRoleTye}
 */
proto.pb_message.PB_AccountLoginHistory.prototype.getRoletype = function() {
  return /** @type {proto.pb_message.PB_AccountLoginHistory.PB_LoginRoleTye} */ (!this.hasRoletype() ? 0 : jspb.Message.getField(this, 2));
};


/** @param {proto.pb_message.PB_AccountLoginHistory.PB_LoginRoleTye|undefined} value  */
proto.pb_message.PB_AccountLoginHistory.prototype.setRoletype = function(value) {
  jspb.Message.setField(this, 2, value);
};


proto.pb_message.PB_AccountLoginHistory.prototype.clearRoletype = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.pb_message.PB_AccountLoginHistory.prototype.hasRoletype = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string roleName = 3;
 * @return {string}
 */
proto.pb_message.PB_AccountLoginHistory.prototype.getRolename = function() {
  return /** @type {string} */ (!this.hasRolename() ? "" : jspb.Message.getField(this, 3));
};


/** @param {string?|undefined} value  */
proto.pb_message.PB_AccountLoginHistory.prototype.setRolename = function(value) {
  jspb.Message.setField(this, 3, value);
};


proto.pb_message.PB_AccountLoginHistory.prototype.clearRolename = function() {
  jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.pb_message.PB_AccountLoginHistory.prototype.hasRolename = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional int32 roleLevel = 4;
 * @return {number}
 */
proto.pb_message.PB_AccountLoginHistory.prototype.getRolelevel = function() {
  return /** @type {number} */ (!this.hasRolelevel() ? 0 : jspb.Message.getField(this, 4));
};


/** @param {number?|undefined} value  */
proto.pb_message.PB_AccountLoginHistory.prototype.setRolelevel = function(value) {
  jspb.Message.setField(this, 4, value);
};


proto.pb_message.PB_AccountLoginHistory.prototype.clearRolelevel = function() {
  jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.pb_message.PB_AccountLoginHistory.prototype.hasRolelevel = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional int32 awakeLevel = 5;
 * @return {number}
 */
proto.pb_message.PB_AccountLoginHistory.prototype.getAwakelevel = function() {
  return /** @type {number} */ (!this.hasAwakelevel() ? 0 : jspb.Message.getField(this, 5));
};


/** @param {number?|undefined} value  */
proto.pb_message.PB_AccountLoginHistory.prototype.setAwakelevel = function(value) {
  jspb.Message.setField(this, 5, value);
};


proto.pb_message.PB_AccountLoginHistory.prototype.clearAwakelevel = function() {
  jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.pb_message.PB_AccountLoginHistory.prototype.hasAwakelevel = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional int32 vipLevel = 6;
 * @return {number}
 */
proto.pb_message.PB_AccountLoginHistory.prototype.getViplevel = function() {
  return /** @type {number} */ (!this.hasViplevel() ? 0 : jspb.Message.getField(this, 6));
};


/** @param {number?|undefined} value  */
proto.pb_message.PB_AccountLoginHistory.prototype.setViplevel = function(value) {
  jspb.Message.setField(this, 6, value);
};


proto.pb_message.PB_AccountLoginHistory.prototype.clearViplevel = function() {
  jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.pb_message.PB_AccountLoginHistory.prototype.hasViplevel = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional int64 updateTime = 7;
 * @return {number}
 */
proto.pb_message.PB_AccountLoginHistory.prototype.getUpdatetime = function() {
  return /** @type {number} */ (!this.hasUpdatetime() ? 0 : jspb.Message.getField(this, 7));
};


/** @param {number?|undefined} value  */
proto.pb_message.PB_AccountLoginHistory.prototype.setUpdatetime = function(value) {
  jspb.Message.setField(this, 7, value);
};


proto.pb_message.PB_AccountLoginHistory.prototype.clearUpdatetime = function() {
  jspb.Message.setField(this, 7, undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.pb_message.PB_AccountLoginHistory.prototype.hasUpdatetime = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * @enum {number}
 */
proto.pb_message.PB_AccountLoginHistory.PB_LoginRoleTye = {
  MAN: 0,
  WOMEN: 1
};


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pb_message.CS11001 = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pb_message.CS11001, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.pb_message.CS11001.displayName = 'proto.pb_message.CS11001';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pb_message.CS11001.prototype.toObject = function(opt_includeInstance) {
  return proto.pb_message.CS11001.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pb_message.CS11001} msg The msg instance to transform.
 * @return {!Object}
 */
proto.pb_message.CS11001.toObject = function(includeInstance, msg) {
  var f, obj = {
    platformtype: jspb.Message.getField(msg, 1),
    platformaccountid: jspb.Message.getField(msg, 2),
    authid: jspb.Message.getField(msg, 3),
    clienttype: jspb.Message.getField(msg, 4),
    uuid: jspb.Message.getField(msg, 5),
    channelid: jspb.Message.getField(msg, 6),
    adchannelid: jspb.Message.getField(msg, 7)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pb_message.CS11001}
 */
proto.pb_message.CS11001.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pb_message.CS11001;
  return proto.pb_message.CS11001.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pb_message.CS11001} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pb_message.CS11001}
 */
proto.pb_message.CS11001.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.pb_message.CS11001.PB_PlatformType} */ (reader.readEnum());
      msg.setPlatformtype(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPlatformaccountid(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setAuthid(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setClienttype(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setUuid(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setChannelid(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setAdchannelid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.pb_message.CS11001} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.pb_message.CS11001.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pb_message.CS11001.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.pb_message.CS11001.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = jspb.Message.getField(this, 1);
  if (f != null) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = jspb.Message.getField(this, 2);
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = jspb.Message.getField(this, 3);
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
  f = jspb.Message.getField(this, 4);
  if (f != null) {
    writer.writeString(
      4,
      f
    );
  }
  f = jspb.Message.getField(this, 5);
  if (f != null) {
    writer.writeString(
      5,
      f
    );
  }
  f = jspb.Message.getField(this, 6);
  if (f != null) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = jspb.Message.getField(this, 7);
  if (f != null) {
    writer.writeInt64(
      7,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.pb_message.CS11001} The clone.
 */
proto.pb_message.CS11001.prototype.cloneMessage = function() {
  return /** @type {!proto.pb_message.CS11001} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional PB_PlatformType platformType = 1;
 * @return {proto.pb_message.CS11001.PB_PlatformType}
 */
proto.pb_message.CS11001.prototype.getPlatformtype = function() {
  return /** @type {proto.pb_message.CS11001.PB_PlatformType} */ (!this.hasPlatformtype() ? 0 : jspb.Message.getField(this, 1));
};


/** @param {proto.pb_message.CS11001.PB_PlatformType|undefined} value  */
proto.pb_message.CS11001.prototype.setPlatformtype = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.pb_message.CS11001.prototype.clearPlatformtype = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.pb_message.CS11001.prototype.hasPlatformtype = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string platformAccountId = 2;
 * @return {string}
 */
proto.pb_message.CS11001.prototype.getPlatformaccountid = function() {
  return /** @type {string} */ (!this.hasPlatformaccountid() ? "" : jspb.Message.getField(this, 2));
};


/** @param {string?|undefined} value  */
proto.pb_message.CS11001.prototype.setPlatformaccountid = function(value) {
  jspb.Message.setField(this, 2, value);
};


proto.pb_message.CS11001.prototype.clearPlatformaccountid = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.pb_message.CS11001.prototype.hasPlatformaccountid = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string authId = 3;
 * @return {string}
 */
proto.pb_message.CS11001.prototype.getAuthid = function() {
  return /** @type {string} */ (!this.hasAuthid() ? "" : jspb.Message.getField(this, 3));
};


/** @param {string?|undefined} value  */
proto.pb_message.CS11001.prototype.setAuthid = function(value) {
  jspb.Message.setField(this, 3, value);
};


proto.pb_message.CS11001.prototype.clearAuthid = function() {
  jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.pb_message.CS11001.prototype.hasAuthid = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string clientType = 4;
 * @return {string}
 */
proto.pb_message.CS11001.prototype.getClienttype = function() {
  return /** @type {string} */ (!this.hasClienttype() ? "" : jspb.Message.getField(this, 4));
};


/** @param {string?|undefined} value  */
proto.pb_message.CS11001.prototype.setClienttype = function(value) {
  jspb.Message.setField(this, 4, value);
};


proto.pb_message.CS11001.prototype.clearClienttype = function() {
  jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.pb_message.CS11001.prototype.hasClienttype = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string uuid = 5;
 * @return {string}
 */
proto.pb_message.CS11001.prototype.getUuid = function() {
  return /** @type {string} */ (!this.hasUuid() ? "" : jspb.Message.getField(this, 5));
};


/** @param {string?|undefined} value  */
proto.pb_message.CS11001.prototype.setUuid = function(value) {
  jspb.Message.setField(this, 5, value);
};


proto.pb_message.CS11001.prototype.clearUuid = function() {
  jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.pb_message.CS11001.prototype.hasUuid = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional int32 channelId = 6;
 * @return {number}
 */
proto.pb_message.CS11001.prototype.getChannelid = function() {
  return /** @type {number} */ (!this.hasChannelid() ? 0 : jspb.Message.getField(this, 6));
};


/** @param {number?|undefined} value  */
proto.pb_message.CS11001.prototype.setChannelid = function(value) {
  jspb.Message.setField(this, 6, value);
};


proto.pb_message.CS11001.prototype.clearChannelid = function() {
  jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.pb_message.CS11001.prototype.hasChannelid = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional int64 adChannelId = 7;
 * @return {number}
 */
proto.pb_message.CS11001.prototype.getAdchannelid = function() {
  return /** @type {number} */ (!this.hasAdchannelid() ? 0 : jspb.Message.getField(this, 7));
};


/** @param {number?|undefined} value  */
proto.pb_message.CS11001.prototype.setAdchannelid = function(value) {
  jspb.Message.setField(this, 7, value);
};


proto.pb_message.CS11001.prototype.clearAdchannelid = function() {
  jspb.Message.setField(this, 7, undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.pb_message.CS11001.prototype.hasAdchannelid = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * @enum {number}
 */
proto.pb_message.CS11001.PacketType = {
  PB_TEMP: 0,
  PB_PACKTYPE: 11001,
  PB_PACKRETTYPE: 11002
};

/**
 * @enum {number}
 */
proto.pb_message.CS11001.PB_PlatformType = {
  LOCAL_LOGIN: 0,
  PLATFORM_LOGIN: 1
};


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pb_message.SC11002 = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.pb_message.SC11002.repeatedFields_, null);
};
goog.inherits(proto.pb_message.SC11002, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.pb_message.SC11002.displayName = 'proto.pb_message.SC11002';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.pb_message.SC11002.repeatedFields_ = [6,7];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pb_message.SC11002.prototype.toObject = function(opt_includeInstance) {
  return proto.pb_message.SC11002.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pb_message.SC11002} msg The msg instance to transform.
 * @return {!Object}
 */
proto.pb_message.SC11002.toObject = function(includeInstance, msg) {
  var f, obj = {
    sessionid: jspb.Message.getField(msg, 1),
    localplayerid: jspb.Message.getField(msg, 2),
    platformaccountid: jspb.Message.getField(msg, 3),
    platformaccountname: jspb.Message.getField(msg, 4),
    accesstoken: jspb.Message.getField(msg, 5),
    loginhistoriesList: jspb.Message.toObjectList(msg.getLoginhistoriesList(),
    proto.pb_message.PB_AccountLoginHistory.toObject, includeInstance),
    serverinfosList: jspb.Message.toObjectList(msg.getServerinfosList(),
    proto.pb_message.PB_ServerInfo.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pb_message.SC11002}
 */
proto.pb_message.SC11002.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pb_message.SC11002;
  return proto.pb_message.SC11002.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pb_message.SC11002} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pb_message.SC11002}
 */
proto.pb_message.SC11002.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSessionid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setLocalplayerid(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setPlatformaccountid(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setPlatformaccountname(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setAccesstoken(value);
      break;
    case 6:
      var value = new proto.pb_message.PB_AccountLoginHistory;
      reader.readMessage(value,proto.pb_message.PB_AccountLoginHistory.deserializeBinaryFromReader);
      msg.getLoginhistoriesList().push(value);
      msg.setLoginhistoriesList(msg.getLoginhistoriesList());
      break;
    case 7:
      var value = new proto.pb_message.PB_ServerInfo;
      reader.readMessage(value,proto.pb_message.PB_ServerInfo.deserializeBinaryFromReader);
      msg.getServerinfosList().push(value);
      msg.setServerinfosList(msg.getServerinfosList());
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.pb_message.SC11002} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.pb_message.SC11002.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pb_message.SC11002.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.pb_message.SC11002.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = jspb.Message.getField(this, 1);
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = jspb.Message.getField(this, 2);
  if (f != null) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = jspb.Message.getField(this, 3);
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
  f = jspb.Message.getField(this, 4);
  if (f != null) {
    writer.writeString(
      4,
      f
    );
  }
  f = jspb.Message.getField(this, 5);
  if (f != null) {
    writer.writeString(
      5,
      f
    );
  }
  f = this.getLoginhistoriesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      proto.pb_message.PB_AccountLoginHistory.serializeBinaryToWriter
    );
  }
  f = this.getServerinfosList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      7,
      f,
      proto.pb_message.PB_ServerInfo.serializeBinaryToWriter
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.pb_message.SC11002} The clone.
 */
proto.pb_message.SC11002.prototype.cloneMessage = function() {
  return /** @type {!proto.pb_message.SC11002} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string sessionId = 1;
 * @return {string}
 */
proto.pb_message.SC11002.prototype.getSessionid = function() {
  return /** @type {string} */ (!this.hasSessionid() ? "" : jspb.Message.getField(this, 1));
};


/** @param {string?|undefined} value  */
proto.pb_message.SC11002.prototype.setSessionid = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.pb_message.SC11002.prototype.clearSessionid = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.pb_message.SC11002.prototype.hasSessionid = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int64 localPlayerId = 2;
 * @return {number}
 */
proto.pb_message.SC11002.prototype.getLocalplayerid = function() {
  return /** @type {number} */ (!this.hasLocalplayerid() ? 0 : jspb.Message.getField(this, 2));
};


/** @param {number?|undefined} value  */
proto.pb_message.SC11002.prototype.setLocalplayerid = function(value) {
  jspb.Message.setField(this, 2, value);
};


proto.pb_message.SC11002.prototype.clearLocalplayerid = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.pb_message.SC11002.prototype.hasLocalplayerid = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string platformAccountId = 3;
 * @return {string}
 */
proto.pb_message.SC11002.prototype.getPlatformaccountid = function() {
  return /** @type {string} */ (!this.hasPlatformaccountid() ? "" : jspb.Message.getField(this, 3));
};


/** @param {string?|undefined} value  */
proto.pb_message.SC11002.prototype.setPlatformaccountid = function(value) {
  jspb.Message.setField(this, 3, value);
};


proto.pb_message.SC11002.prototype.clearPlatformaccountid = function() {
  jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.pb_message.SC11002.prototype.hasPlatformaccountid = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string platformAccountName = 4;
 * @return {string}
 */
proto.pb_message.SC11002.prototype.getPlatformaccountname = function() {
  return /** @type {string} */ (!this.hasPlatformaccountname() ? "" : jspb.Message.getField(this, 4));
};


/** @param {string?|undefined} value  */
proto.pb_message.SC11002.prototype.setPlatformaccountname = function(value) {
  jspb.Message.setField(this, 4, value);
};


proto.pb_message.SC11002.prototype.clearPlatformaccountname = function() {
  jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.pb_message.SC11002.prototype.hasPlatformaccountname = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string accessToken = 5;
 * @return {string}
 */
proto.pb_message.SC11002.prototype.getAccesstoken = function() {
  return /** @type {string} */ (!this.hasAccesstoken() ? "" : jspb.Message.getField(this, 5));
};


/** @param {string?|undefined} value  */
proto.pb_message.SC11002.prototype.setAccesstoken = function(value) {
  jspb.Message.setField(this, 5, value);
};


proto.pb_message.SC11002.prototype.clearAccesstoken = function() {
  jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.pb_message.SC11002.prototype.hasAccesstoken = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * repeated PB_AccountLoginHistory loginHistories = 6;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.pb_message.PB_AccountLoginHistory>}
 */
proto.pb_message.SC11002.prototype.getLoginhistoriesList = function() {
  return /** @type{!Array.<!proto.pb_message.PB_AccountLoginHistory>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.pb_message.PB_AccountLoginHistory, 6));
};


/** @param {Array.<!proto.pb_message.PB_AccountLoginHistory>} value  */
proto.pb_message.SC11002.prototype.setLoginhistoriesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 6, value);
};


proto.pb_message.SC11002.prototype.clearLoginhistoriesList = function() {
  this.setLoginhistoriesList([]);
};


/**
 * repeated PB_ServerInfo serverInfos = 7;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.pb_message.PB_ServerInfo>}
 */
proto.pb_message.SC11002.prototype.getServerinfosList = function() {
  return /** @type{!Array.<!proto.pb_message.PB_ServerInfo>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.pb_message.PB_ServerInfo, 7));
};


/** @param {Array.<!proto.pb_message.PB_ServerInfo>} value  */
proto.pb_message.SC11002.prototype.setServerinfosList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 7, value);
};


proto.pb_message.SC11002.prototype.clearServerinfosList = function() {
  this.setServerinfosList([]);
};


/**
 * @enum {number}
 */
proto.pb_message.SC11002.PacketType = {
  PB_TEMP: 0,
  PB_PACKTYPE: 10001
};

goog.object.extend(exports, proto.pb_message);
